CREATE TABLE bank (
    bank_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    bank_code    VARCHAR2(20 CHAR)  NOT NULL,
    legal_name   VARCHAR2(200 CHAR) NOT NULL,
    display_name VARCHAR2(200 CHAR) NOT NULL,
    is_active    CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_bank PRIMARY KEY (bank_id),
    CONSTRAINT uq_bank_code UNIQUE (bank_code),
    CONSTRAINT ck_bank_code_uppercase CHECK (bank_code = UPPER(bank_code)),
    CONSTRAINT ck_bank_is_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE branch (
    branch_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    bank_id        NUMBER(19) NOT NULL,
    branch_code    VARCHAR2(20 CHAR)  NOT NULL,
    branch_name    VARCHAR2(200 CHAR) NOT NULL,
    ifsc_code      VARCHAR2(11 CHAR)  NOT NULL,
    email          VARCHAR2(254 CHAR),
    phone_number   VARCHAR2(30 CHAR),
    address_line_1 VARCHAR2(200 CHAR) NOT NULL,
    address_line_2 VARCHAR2(200 CHAR),
    city           VARCHAR2(100 CHAR) NOT NULL,
    state          VARCHAR2(100 CHAR) NOT NULL,
    postal_code    VARCHAR2(20 CHAR)  NOT NULL,
    is_active      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_branch PRIMARY KEY (branch_id),
    CONSTRAINT fk_branch_bank FOREIGN KEY (bank_id)
        REFERENCES bank (bank_id),
    CONSTRAINT uq_branch_bank_code UNIQUE (bank_id, branch_code),
    CONSTRAINT uq_branch_ifsc_code UNIQUE (ifsc_code),
    CONSTRAINT ck_branch_code_uppercase CHECK (branch_code = UPPER(branch_code)),
    CONSTRAINT ck_branch_ifsc_uppercase CHECK (ifsc_code = UPPER(ifsc_code)),
    CONSTRAINT ck_branch_ifsc_format CHECK (
        REGEXP_LIKE(ifsc_code, '^[A-Z]{4}0[A-Z0-9]{6}$')
    ),
    CONSTRAINT ck_branch_is_active CHECK (is_active IN ('Y', 'N'))
);


CREATE OR REPLACE TRIGGER trg_bank_set_updated_at
BEFORE UPDATE ON bank
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_branch_set_updated_at
BEFORE UPDATE ON branch
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE bank_account (
    account_id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    branch_id          NUMBER(19) NOT NULL,
    account_number     VARCHAR2(20 CHAR) NOT NULL,
    account_type       VARCHAR2(20 CHAR) NOT NULL,
    currency_code      CHAR(3 CHAR) DEFAULT 'INR' NOT NULL,
    account_status     VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    current_balance    NUMBER(19,4) DEFAULT 0 NOT NULL,
    available_balance  NUMBER(19,4) DEFAULT 0 NOT NULL,
    opened_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    closed_at          TIMESTAMP(6),
    created_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_bank_account PRIMARY KEY (account_id),
    CONSTRAINT fk_bank_account_branch FOREIGN KEY (branch_id)
        REFERENCES branch (branch_id),
    CONSTRAINT uq_bank_account_number UNIQUE (account_number),
    CONSTRAINT ck_bank_account_type CHECK (
        account_type IN ('SAVINGS', 'CURRENT')
    ),
    CONSTRAINT ck_bank_account_currency CHECK (currency_code = UPPER(currency_code)),
    CONSTRAINT ck_bank_account_status CHECK (
        account_status IN ('PENDING', 'ACTIVE', 'FROZEN', 'CLOSED')
    ),
    CONSTRAINT ck_bank_account_number CHECK (REGEXP_LIKE(account_number, '^[0-9]{10,20}$')),
    CONSTRAINT ck_bank_account_balances CHECK (
        current_balance >= 0
        AND available_balance >= 0
        AND available_balance <= current_balance
    ),
    CONSTRAINT ck_bank_account_closed CHECK (
        (account_status = 'CLOSED' AND closed_at IS NOT NULL)
        OR account_status <> 'CLOSED'
    )
);

CREATE TABLE account_holder (
    account_id       NUMBER(19) NOT NULL,
    customer_id      NUMBER(19) NOT NULL,
    holder_type      VARCHAR2(20 CHAR) DEFAULT 'PRIMARY' NOT NULL,
    is_active        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    joined_at        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_account_holder PRIMARY KEY (account_id, customer_id),
    CONSTRAINT fk_account_holder_account FOREIGN KEY (account_id)
        REFERENCES bank_account (account_id),
    CONSTRAINT ck_account_holder_type CHECK (
        holder_type IN ('PRIMARY', 'JOINT')
    ),
    CONSTRAINT ck_account_holder_active CHECK (is_active IN ('Y', 'N'))
);

CREATE INDEX ix_account_holder_customer ON account_holder (customer_id);

CREATE OR REPLACE TRIGGER trg_bank_account_set_updated_at
BEFORE UPDATE ON bank_account
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE bank_transaction (
    transaction_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    transaction_reference VARCHAR2(50 CHAR) NOT NULL,
    debit_account_id     NUMBER(19),
    credit_account_id    NUMBER(19),
    beneficiary_id       NUMBER(19),
    initiated_by_user_id NUMBER(19),
    transaction_type     VARCHAR2(30 CHAR) NOT NULL,
    transaction_status   VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    amount               NUMBER(19,4) NOT NULL,
    currency_code        CHAR(3 CHAR) DEFAULT 'INR' NOT NULL,
    narration            VARCHAR2(500 CHAR),
    initiated_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    completed_at         TIMESTAMP(6),
    failure_reason       VARCHAR2(500 CHAR),
    created_at           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_bank_transaction PRIMARY KEY (transaction_id),
    CONSTRAINT uq_bank_transaction_ref UNIQUE (transaction_reference),
    CONSTRAINT fk_bank_txn_debit_account FOREIGN KEY (debit_account_id)
        REFERENCES bank_account (account_id),
    CONSTRAINT fk_bank_txn_credit_account FOREIGN KEY (credit_account_id)
        REFERENCES bank_account (account_id),
    CONSTRAINT ck_bank_txn_type CHECK (
        transaction_type IN ('TRANSFER', 'DEPOSIT', 'WITHDRAWAL', 'LOAN_PAYMENT', 'REVERSAL')
    ),
    CONSTRAINT ck_bank_txn_status CHECK (
        transaction_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED')
    ),
    CONSTRAINT ck_bank_txn_amount CHECK (amount > 0),
    CONSTRAINT ck_bank_txn_currency CHECK (currency_code = UPPER(currency_code)),
    CONSTRAINT ck_bank_txn_accounts CHECK (
        debit_account_id IS NULL
        OR credit_account_id IS NULL
        OR debit_account_id <> credit_account_id
    ),
    CONSTRAINT ck_bank_txn_completed CHECK (
        (transaction_status IN ('COMPLETED', 'REVERSED') AND completed_at IS NOT NULL)
        OR transaction_status NOT IN ('COMPLETED', 'REVERSED')
    )
);

CREATE TABLE account_transaction_entry (
    entry_id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    transaction_id   NUMBER(19) NOT NULL,
    account_id       NUMBER(19) NOT NULL,
    entry_type       VARCHAR2(10 CHAR) NOT NULL,
    amount           NUMBER(19,4) NOT NULL,
    balance_after    NUMBER(19,4) NOT NULL,
    posted_at        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_account_transaction_entry PRIMARY KEY (entry_id),
    CONSTRAINT fk_account_entry_transaction FOREIGN KEY (transaction_id)
        REFERENCES bank_transaction (transaction_id),
    CONSTRAINT fk_account_entry_account FOREIGN KEY (account_id)
        REFERENCES bank_account (account_id),
    CONSTRAINT uq_account_entry UNIQUE (transaction_id, account_id, entry_type),
    CONSTRAINT ck_account_entry_type CHECK (entry_type IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ck_account_entry_amount CHECK (amount > 0),
    CONSTRAINT ck_account_entry_balance CHECK (balance_after >= 0)
);

CREATE INDEX ix_bank_txn_debit_account ON bank_transaction (debit_account_id, initiated_at);
CREATE INDEX ix_bank_txn_credit_account ON bank_transaction (credit_account_id, initiated_at);
CREATE INDEX ix_account_entry_account_time ON account_transaction_entry (account_id, posted_at);

CREATE OR REPLACE TRIGGER trg_bank_transaction_set_updated
BEFORE UPDATE ON bank_transaction
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE bank_transaction_status_history (
    status_history_id   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    transaction_id      NUMBER(19) NOT NULL,
    previous_status     VARCHAR2(20 CHAR),
    new_status          VARCHAR2(20 CHAR) NOT NULL,
    failure_reason      VARCHAR2(500 CHAR),
    changed_by_user_id  NUMBER(19),
    changed_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_bank_txn_status_history PRIMARY KEY (status_history_id),
    CONSTRAINT fk_bank_txn_status_txn FOREIGN KEY (transaction_id)
        REFERENCES bank_transaction (transaction_id),
    CONSTRAINT ck_bank_txn_previous_status CHECK (
        previous_status IS NULL
        OR previous_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED')
    ),
    CONSTRAINT ck_bank_txn_new_status CHECK (
        new_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED')
    ),
    CONSTRAINT ck_bank_txn_status_changed CHECK (
        previous_status IS NULL OR previous_status <> new_status
    ),
    CONSTRAINT ck_bank_txn_failure_reason CHECK (
        (new_status = 'FAILED' AND failure_reason IS NOT NULL)
        OR (new_status <> 'FAILED' AND failure_reason IS NULL)
    )
);

CREATE INDEX ix_bank_txn_status_history
    ON bank_transaction_status_history (transaction_id, changed_at, status_history_id);
CREATE TABLE ledger_operation (
    caller VARCHAR2(50 CHAR) NOT NULL,
    operation_id VARCHAR2(64 CHAR) NOT NULL,
    request_fingerprint VARCHAR2(64 CHAR) NOT NULL,
    receipt CLOB,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_ledger_operation PRIMARY KEY(caller,operation_id)
);
