CREATE TABLE external_transfer_dispatch (
    external_transfer_dispatch_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    operation_id                  VARCHAR2(64 CHAR) NOT NULL,
    transaction_id                NUMBER(19) NOT NULL,
    provider_reference            VARCHAR2(100 CHAR) NOT NULL,
    dispatch_status               VARCHAR2(20 CHAR) NOT NULL,
    dispatched_at                 TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_external_transfer_dispatch PRIMARY KEY (external_transfer_dispatch_id),
    CONSTRAINT uq_external_transfer_operation UNIQUE (operation_id),
    CONSTRAINT uq_external_transfer_provider_ref UNIQUE (provider_reference),
    CONSTRAINT fk_external_transfer_transaction FOREIGN KEY (transaction_id)
        REFERENCES bank_transaction (transaction_id),
    CONSTRAINT ck_external_transfer_status CHECK (dispatch_status IN ('ACCEPTED'))
);

CREATE INDEX ix_external_transfer_transaction
    ON external_transfer_dispatch (transaction_id);
