spring.application.name=identity-service
server.port=${SERVER_PORT:8081}
spring.config.import=classpath:runtime.properties
app.events.enabled=true
app.security.jwt.private-key=${JWT_PRIVATE_KEY}
app.security.jwt.expiration-minutes=15
app.security.totp.encryption-key=${TOTP_ENCRYPTION_KEY}
app.security.totp.login-challenge-minutes=5
app.security.otp-expiry-minutes=5
app.security.max-failed-login-attempts=5
app.security.account-lock-minutes=15
