spring.application.name=identity-service
server.port=${SERVER_PORT:8081}
spring.config.import=classpath:runtime.properties
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@//127.0.0.1:1521/FREEPDB1}
spring.datasource.username=${DB_USERNAME:NB_IDENTITY}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.user=${MIGRATION_USERNAME:${spring.datasource.username}}
spring.flyway.password=${MIGRATION_PASSWORD:${spring.datasource.password}}
app.events.enabled=true
app.security.jwt.private-key=${JWT_PRIVATE_KEY}
app.security.jwt.expiration-minutes=15
app.security.totp.encryption-key=${TOTP_ENCRYPTION_KEY}
app.security.totp.login-challenge-minutes=5
app.security.otp-expiry-minutes=5
app.security.max-failed-login-attempts=5
app.security.account-lock-minutes=15
spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type=TIMESTAMP
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
