package com.netbanking.payment.service;

import static org.assertj.core.api.Assertions.*;

import com.netbanking.ServiceTestBase;
import com.netbanking.contracts.*;

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;

class PaymentWorkflowIntegrationTest extends ServiceTestBase {
    @Autowired PaymentWorkflowStore store;
    @Autowired JdbcTemplate jdbc;
    final LedgerCommand command =
            new LedgerCommand(
                    "operation-key",
                    7L,
                    10L,
                    "1234567890",
                    "ABCD0001234",
                    "TRANSFER",
                    new BigDecimal("100"),
                    "INR",
                    "Rent");

    @BeforeEach
    void tables() {
        jdbc.execute(
                "CREATE TABLE IF NOT EXISTS payment_operation(payment_id BIGINT GENERATED BY"
                    + " DEFAULT AS IDENTITY PRIMARY KEY,kind VARCHAR(20),operation_key VARCHAR(64)"
                    + " UNIQUE,user_id BIGINT,request_key VARCHAR(100),request_fingerprint"
                    + " VARCHAR(64),intent_digest VARCHAR(64),ledger_command CLOB,payment_details"
                    + " CLOB,state VARCHAR(20),transaction_id BIGINT,transaction_reference"
                    + " VARCHAR(50),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,next_attempt_at"
                    + " TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,kind,request_key))");
        jdbc.execute(
                "CREATE TABLE IF NOT EXISTS event_outbox(event_id VARCHAR(36) PRIMARY"
                    + " KEY,destination VARCHAR(50),envelope CLOB)");
        jdbc.update("DELETE FROM payment_operation");
        jdbc.update("DELETE FROM event_outbox");
    }

    void create() {
        store.create(
                "TRANSFER",
                "request-key",
                "a".repeat(64),
                "b".repeat(64),
                command,
                new PaymentWorkflowStore.Details(20L, null, null, "Rent"));
    }

    @Test
    void authorizationReceiptAndEventsSurviveSeparateTransactions() {
        create();
        assertThat(store.recoverable()).isEmpty();
        store.authorized(command.operationId());
        assertThat(store.recoverable()).hasSize(1);
        var receipt = new LedgerReceipt(55L, "TXN-55", "COMPLETED", command.amount(), "INR");
        var first = store.complete(command.operationId(), receipt);
        assertThat(store.complete(command.operationId(), receipt)).isEqualTo(first);
        assertThat(store.history(7L, "TRANSFER")).hasSize(1);
        assertThat(store.history(8L, "TRANSFER")).isEmpty();
        assertThat(store.recoverable()).isEmpty();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM event_outbox", Integer.class))
                .isEqualTo(2);
        assertThat(
                        jdbc.queryForObject(
                                "SELECT payment_details FROM payment_operation", String.class))
                .contains("beneficiaryId")
                .doesNotContain("otp");
    }

    @Test
    void retrySchedulingAndReceiptMismatchKeepTheOperationRecoverable() {
        create();
        store.authorized(command.operationId());
        assertThatThrownBy(
                        () ->
                                store.complete(
                                        command.operationId(),
                                        new LedgerReceipt(
                                                55L,
                                                "TXN-55",
                                                "COMPLETED",
                                                new BigDecimal("101"),
                                                "INR")))
                .isInstanceOf(IllegalStateException.class);
        assertThat(store.get(command.operationId()).state()).isEqualTo("AUTHORIZED");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM event_outbox", Integer.class))
                .isZero();
        store.defer(command.operationId());
        assertThat(store.recoverable()).isEmpty();
        jdbc.update(
                "UPDATE payment_operation SET next_attempt_at = TIMESTAMP '2000-01-01 00:00:00'");
        assertThat(store.recoverable()).hasSize(1);
    }
}
