package com.netbanking.payment.service;

import static org.assertj.core.api.Assertions.*;

import com.netbanking.ServiceTestBase;
import com.netbanking.common.exception.ResourceNotFoundException;
import com.netbanking.biller.provider.BillerPaymentReceipt;

import com.netbanking.contracts.*;
import com.netbanking.payment.api.PaymentKind;
import com.netbanking.payment.api.PaymentSearchFilter;
import com.netbanking.payment.api.PaymentStatus;

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;

class PaymentWorkflowIntegrationTest extends ServiceTestBase {
    @Autowired PaymentWorkflowStore store;
    @Autowired PaymentSearchService search;
    @Autowired JdbcTemplate jdbc;
    final LedgerCommand command =
            new LedgerCommand(
                    "operation-key",
                    7L,
                    10L,
                    20L,
                    "1234567890",
                    "ABCD0001234",
                    "TRANSFER",
                    new BigDecimal("100"),
                    "INR",
                    "Rent");

    @BeforeEach
    void tables() {
        jdbc.execute(
                "CREATE TABLE IF NOT EXISTS payment_operation(payment_id BIGINT GENERATED BY"
                    + " DEFAULT AS IDENTITY PRIMARY KEY,kind VARCHAR(20),operation_key VARCHAR(64)"
                    + " UNIQUE,user_id BIGINT,request_key VARCHAR(100),request_fingerprint"
                    + " VARCHAR(64),intent_digest VARCHAR(64),ledger_command CLOB,payment_details"
                    + " CLOB,state VARCHAR(20),transaction_id BIGINT,transaction_reference"
                    + " VARCHAR(50),provider_reference VARCHAR(100),provider_status VARCHAR(20),"
                    + " reversal_transaction_id BIGINT,reversal_transaction_reference"
                    + " VARCHAR(50),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,next_attempt_at"
                    + " TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,kind,request_key))");
        jdbc.execute(
                "CREATE TABLE IF NOT EXISTS event_outbox(event_id VARCHAR(36) PRIMARY"
                    + " KEY,destination VARCHAR(50),envelope CLOB)");
        jdbc.update("DELETE FROM payment_operation");
        jdbc.update("DELETE FROM event_outbox");
    }

    void create() {
        store.create(
                "TRANSFER",
                "request-key",
                "a".repeat(64),
                "b".repeat(64),
                command,
                new PaymentWorkflowStore.Details(20L, null, null, null, "Rent"));
    }

    LedgerCommand createBill(String operationKey, String requestKey) {
        var bill =
                new LedgerCommand(
                        operationKey,
                        7L,
                        10L,
                        null,
                        null,
                        "WITHDRAWAL",
                        new BigDecimal("100"),
                        "INR",
                        "Bill payment: WATER");
        store.create(
                "BILL_PAYMENT",
                requestKey,
                "c".repeat(64),
                "d".repeat(64),
                bill,
                new PaymentWorkflowStore.Details(
                        null, 3L, "WATER", "ABC-123", null));
        store.authorized(operationKey);
        return bill;
    }

    @Test
    void authorizationReceiptAndEventsSurviveSeparateTransactions() {
        create();
        assertThat(store.recoverable()).isEmpty();
        store.authorized(command.operationId());
        assertThat(store.recoverable()).hasSize(1);
        var receipt = new LedgerReceipt(55L, "TXN-55", "COMPLETED", command.amount(), "INR");
        var first = store.complete(command.operationId(), receipt);
        assertThat(store.complete(command.operationId(), receipt)).isEqualTo(first);
        assertThat(store.history(7L, "TRANSFER")).hasSize(1);
        assertThat(store.history(8L, "TRANSFER")).isEmpty();
        assertThat(store.recoverable()).isEmpty();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM event_outbox", Integer.class))
                .isEqualTo(2);
        assertThat(
                        jdbc.queryForObject(
                                "SELECT payment_details FROM payment_operation", String.class))
                .contains("beneficiaryId")
                .doesNotContain("otp");
    }

    @Test
    void retrySchedulingAndReceiptMismatchKeepTheOperationRecoverable() {
        create();
        store.authorized(command.operationId());
        assertThatThrownBy(
                        () ->
                                store.complete(
                                        command.operationId(),
                                        new LedgerReceipt(
                                                55L,
                                                "TXN-55",
                                                "COMPLETED",
                                                new BigDecimal("101"),
                                                "INR")))
                .isInstanceOf(IllegalStateException.class);
        assertThat(store.get(command.operationId()).state()).isEqualTo("AUTHORIZED");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM event_outbox", Integer.class))
                .isZero();
        store.defer(command.operationId());
        assertThat(store.recoverable()).isEmpty();
        jdbc.update(
                "UPDATE payment_operation SET next_attempt_at = TIMESTAMP '2000-01-01 00:00:00'");
        assertThat(store.recoverable()).hasSize(1);
    }

    @Test
    void acceptedBillerReceiptCompletesARecordedDebit() {
        var bill = createBill("bill-accepted", "bill-request-1");
        var debit = new LedgerReceipt(61L, "TXN-61", "COMPLETED", bill.amount(), "INR");
        var provider = new BillerPaymentReceipt("PROVIDER-61", "ACCEPTED", null);

        store.debited(bill.operationId(), debit);
        var completed = store.completeBill(bill.operationId(), debit, provider);

        assertThat(completed.status()).isEqualTo("COMPLETED");
        assertThat(store.details(bill.operationId()).billerCode()).isEqualTo("WATER");
        assertThat(store.recoverable()).isEmpty();
        assertThat(
                        jdbc.queryForObject(
                                "SELECT provider_reference FROM payment_operation WHERE"
                                        + " operation_key = ?",
                                String.class,
                                bill.operationId()))
                .isEqualTo("PROVIDER-61");
    }

    @Test
    void rejectedBillerReceiptPersistsTheCompensatingTransaction() {
        var bill = createBill("bill-rejected", "bill-request-2");
        var debit = new LedgerReceipt(71L, "TXN-71", "COMPLETED", bill.amount(), "INR");
        var reversal = new LedgerReceipt(72L, "TXN-72", "COMPLETED", bill.amount(), "INR");
        var provider =
                new BillerPaymentReceipt("PROVIDER-71", "REJECTED", "Reference closed");

        store.debited(bill.operationId(), debit);
        var reversed = store.reversed(bill.operationId(), debit, reversal, provider);

        assertThat(reversed.status()).isEqualTo("REVERSED");
        assertThat(store.reversed(bill.operationId(), debit, reversal, provider))
                .isEqualTo(reversed);
        assertThat(
                        jdbc.queryForObject(
                                "SELECT reversal_transaction_reference FROM payment_operation"
                                        + " WHERE operation_key = ?",
                                String.class,
                                bill.operationId()))
                .isEqualTo("TXN-72");
    }

    @Test
    void paymentSearchFiltersResultsAndEnforcesOwnership() {
        create();
        store.authorized(command.operationId());
        store.complete(
                command.operationId(),
                new LedgerReceipt(55L, "TXN-55", "COMPLETED", command.amount(), "INR"));

        var result =
                search.search(
                        7L,
                        new PaymentSearchFilter(
                                PaymentKind.TRANSFER,
                                PaymentStatus.COMPLETED,
                                null,
                                null,
                                "TXN-55"),
                        0,
                        20);

        assertThat(result.getTotalElements()).isEqualTo(1);
        var payment = result.getContent().get(0);
        assertThat(payment.transactionReference()).isEqualTo("TXN-55");
        assertThat(payment.sourceAccountId()).isEqualTo(10L);
        assertThat(payment.beneficiaryId()).isEqualTo(20L);
        assertThat(payment.narration()).isEqualTo("Rent");
        assertThat(search.get(7L, payment.paymentId())).isEqualTo(payment);
        assertThatThrownBy(() -> search.get(8L, payment.paymentId()))
                .isInstanceOf(ResourceNotFoundException.class);

    }
}
