CREATE TABLE notification (
    notification_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id         NUMBER(19) NOT NULL,
    notification_type VARCHAR2(50 CHAR) NOT NULL,
    title           VARCHAR2(200 CHAR) NOT NULL,
    message         VARCHAR2(1000 CHAR) NOT NULL,
    is_read         CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    created_at      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    read_at         TIMESTAMP(6),
    CONSTRAINT pk_notification PRIMARY KEY (notification_id),
    CONSTRAINT ck_notification_read CHECK (is_read IN ('Y', 'N'))
);
CREATE INDEX ix_notification_user_time ON notification (user_id, created_at);

CREATE TABLE notification_delivery (
    notification_delivery_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    notification_id NUMBER(19) NOT NULL,
    channel          VARCHAR2(20 CHAR) NOT NULL,
    delivery_status  VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    attempted_at     TIMESTAMP(6),
    failure_reason   VARCHAR2(500 CHAR),
    CONSTRAINT pk_notification_delivery PRIMARY KEY (notification_delivery_id),
    CONSTRAINT fk_notification_delivery_notification FOREIGN KEY (notification_id) REFERENCES notification (notification_id),
    CONSTRAINT ck_notification_delivery_channel CHECK (channel IN ('IN_APP', 'EMAIL', 'SMS')),
    CONSTRAINT ck_notification_delivery_status CHECK (delivery_status IN ('PENDING', 'SENT', 'FAILED'))
);
CREATE INDEX ix_notification_delivery_notification ON notification_delivery (notification_id);
