-- Internet Net Banking Application
-- Bank and branch foundation
--
-- Run as NET_BANKING_APP while connected to FREEPDB1.
-- Run as a script (Run -> Run Script or F5) in Oracle SQL Developer.
-- Do not run this script a second time after the tables exist.

SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE bank (
    bank_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    bank_code    VARCHAR2(20 CHAR)  NOT NULL,
    legal_name   VARCHAR2(200 CHAR) NOT NULL,
    display_name VARCHAR2(200 CHAR) NOT NULL,
    is_active    CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_bank PRIMARY KEY (bank_id),
    CONSTRAINT uq_bank_code UNIQUE (bank_code),
    CONSTRAINT ck_bank_code_uppercase CHECK (bank_code = UPPER(bank_code)),
    CONSTRAINT ck_bank_is_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE branch (
    branch_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    bank_id        NUMBER(19) NOT NULL,
    branch_code    VARCHAR2(20 CHAR)  NOT NULL,
    branch_name    VARCHAR2(200 CHAR) NOT NULL,
    ifsc_code      VARCHAR2(11 CHAR)  NOT NULL,
    email          VARCHAR2(254 CHAR),
    phone_number   VARCHAR2(30 CHAR),
    address_line_1 VARCHAR2(200 CHAR) NOT NULL,
    address_line_2 VARCHAR2(200 CHAR),
    city           VARCHAR2(100 CHAR) NOT NULL,
    state          VARCHAR2(100 CHAR) NOT NULL,
    postal_code    VARCHAR2(20 CHAR)  NOT NULL,
    is_active      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_branch PRIMARY KEY (branch_id),
    CONSTRAINT fk_branch_bank FOREIGN KEY (bank_id)
        REFERENCES bank (bank_id),
    CONSTRAINT uq_branch_bank_code UNIQUE (bank_id, branch_code),
    CONSTRAINT uq_branch_ifsc_code UNIQUE (ifsc_code),
    CONSTRAINT ck_branch_code_uppercase CHECK (branch_code = UPPER(branch_code)),
    CONSTRAINT ck_branch_ifsc_uppercase CHECK (ifsc_code = UPPER(ifsc_code)),
    CONSTRAINT ck_branch_ifsc_format CHECK (
        REGEXP_LIKE(ifsc_code, '^[A-Z]{4}0[A-Z0-9]{6}$')
    ),
    CONSTRAINT ck_branch_is_active CHECK (is_active IN ('Y', 'N'))
);

-- UQ_BRANCH_BANK_CODE creates an index beginning with BANK_ID.
-- No extra BANK_ID-only index is needed at this stage.

CREATE OR REPLACE TRIGGER trg_bank_set_updated_at
BEFORE UPDATE ON bank
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_branch_set_updated_at
BEFORE UPDATE ON branch
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

PROMPT Bank and branch tables created successfully.

WHENEVER SQLERROR CONTINUE NONE
