-- Internet Net Banking Application
-- Banking transaction records and account ledger entries
--
-- Run after 04_account_tables.sql and 05_beneficiary_tables.sql.
-- Run as NET_BANKING_APP while connected to FREEPDB1.
-- Run as a script (Run -> Run Script or F5) in Oracle SQL Developer.
-- Do not run this script a second time after the tables exist.

SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE bank_transaction (
    transaction_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    transaction_reference VARCHAR2(50 CHAR) NOT NULL,
    debit_account_id     NUMBER(19),
    credit_account_id    NUMBER(19),
    beneficiary_id       NUMBER(19),
    initiated_by_user_id NUMBER(19),
    transaction_type     VARCHAR2(30 CHAR) NOT NULL,
    transaction_status   VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    amount               NUMBER(19,4) NOT NULL,
    currency_code        CHAR(3 CHAR) DEFAULT 'INR' NOT NULL,
    narration            VARCHAR2(500 CHAR),
    initiated_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    completed_at         TIMESTAMP(6),
    failure_reason       VARCHAR2(500 CHAR),
    created_at           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_bank_transaction PRIMARY KEY (transaction_id),
    CONSTRAINT uq_bank_transaction_ref UNIQUE (transaction_reference),
    CONSTRAINT fk_bank_txn_debit_account FOREIGN KEY (debit_account_id)
        REFERENCES bank_account (account_id),
    CONSTRAINT fk_bank_txn_credit_account FOREIGN KEY (credit_account_id)
        REFERENCES bank_account (account_id),
    CONSTRAINT fk_bank_txn_beneficiary FOREIGN KEY (beneficiary_id)
        REFERENCES beneficiary (beneficiary_id),
    CONSTRAINT fk_bank_txn_initiated_user FOREIGN KEY (initiated_by_user_id)
        REFERENCES app_user (user_id),
    CONSTRAINT ck_bank_txn_type CHECK (
        transaction_type IN ('TRANSFER', 'DEPOSIT', 'WITHDRAWAL', 'REVERSAL')
    ),
    CONSTRAINT ck_bank_txn_status CHECK (
        transaction_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED')
    ),
    CONSTRAINT ck_bank_txn_amount CHECK (amount > 0),
    CONSTRAINT ck_bank_txn_currency CHECK (currency_code = UPPER(currency_code)),
    CONSTRAINT ck_bank_txn_accounts CHECK (
        debit_account_id IS NULL
        OR credit_account_id IS NULL
        OR debit_account_id <> credit_account_id
    ),
    CONSTRAINT ck_bank_txn_completed CHECK (
        (transaction_status IN ('COMPLETED', 'REVERSED') AND completed_at IS NOT NULL)
        OR transaction_status NOT IN ('COMPLETED', 'REVERSED')
    )
);

CREATE TABLE account_transaction_entry (
    entry_id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    transaction_id   NUMBER(19) NOT NULL,
    account_id       NUMBER(19) NOT NULL,
    entry_type       VARCHAR2(10 CHAR) NOT NULL,
    amount           NUMBER(19,4) NOT NULL,
    balance_after    NUMBER(19,4) NOT NULL,
    posted_at        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_account_transaction_entry PRIMARY KEY (entry_id),
    CONSTRAINT fk_account_entry_transaction FOREIGN KEY (transaction_id)
        REFERENCES bank_transaction (transaction_id),
    CONSTRAINT fk_account_entry_account FOREIGN KEY (account_id)
        REFERENCES bank_account (account_id),
    CONSTRAINT uq_account_entry UNIQUE (transaction_id, account_id, entry_type),
    CONSTRAINT ck_account_entry_type CHECK (entry_type IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ck_account_entry_amount CHECK (amount > 0),
    CONSTRAINT ck_account_entry_balance CHECK (balance_after >= 0)
);

CREATE INDEX ix_bank_txn_debit_account ON bank_transaction (debit_account_id, initiated_at);
CREATE INDEX ix_bank_txn_credit_account ON bank_transaction (credit_account_id, initiated_at);
CREATE INDEX ix_account_entry_account_time ON account_transaction_entry (account_id, posted_at);

CREATE OR REPLACE TRIGGER trg_bank_transaction_set_updated
BEFORE UPDATE ON bank_transaction
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

PROMPT Transaction tables created successfully.

WHENEVER SQLERROR CONTINUE NONE
