-- Internet Net Banking Application
-- Login attempts and application audit events
--
-- Run as NET_BANKING_APP while connected to FREEPDB1.
-- Run as a script (Run -> Run Script or F5) in Oracle SQL Developer.
-- Do not run this script a second time after the tables exist.
-- Never store passwords, password hashes, tokens, or complete card/account data here.

SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE login_audit (
    login_audit_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id             NUMBER(19),
    username_attempted  VARCHAR2(100 CHAR) NOT NULL,
    login_outcome       VARCHAR2(20 CHAR) NOT NULL,
    failure_reason      VARCHAR2(200 CHAR),
    client_ip_address   VARCHAR2(45 CHAR),
    user_agent          VARCHAR2(500 CHAR),
    occurred_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_login_audit PRIMARY KEY (login_audit_id),
    CONSTRAINT fk_login_audit_user FOREIGN KEY (user_id)
        REFERENCES app_user (user_id),
    CONSTRAINT ck_login_audit_outcome CHECK (login_outcome IN ('SUCCESS', 'FAILURE'))
);

CREATE TABLE audit_event (
    audit_event_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id             NUMBER(19),
    event_type          VARCHAR2(100 CHAR) NOT NULL,
    entity_type         VARCHAR2(100 CHAR),
    entity_id           VARCHAR2(100 CHAR),
    outcome             VARCHAR2(20 CHAR) DEFAULT 'SUCCESS' NOT NULL,
    request_id          VARCHAR2(100 CHAR),
    client_ip_address   VARCHAR2(45 CHAR),
    event_details       CLOB,
    occurred_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_audit_event PRIMARY KEY (audit_event_id),
    CONSTRAINT fk_audit_event_user FOREIGN KEY (user_id)
        REFERENCES app_user (user_id),
    CONSTRAINT ck_audit_event_outcome CHECK (
        outcome IN ('SUCCESS', 'FAILURE', 'DENIED')
    )
);

CREATE INDEX ix_login_audit_user_time ON login_audit (user_id, occurred_at);
CREATE INDEX ix_audit_event_user_time ON audit_event (user_id, occurred_at);
CREATE INDEX ix_audit_event_entity ON audit_event (entity_type, entity_id);

PROMPT Audit and security tables created successfully.

WHENEVER SQLERROR CONTINUE NONE
