-- Identity and OTP extension.
-- Run after 01_security_tables.sql and 07_audit_security_tables.sql.

ALTER TABLE app_user ADD (
    locked_until TIMESTAMP(6)
);

CREATE TABLE otp_verification (
    otp_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id            NUMBER(19) NOT NULL,
    challenge_id       VARCHAR2(100 CHAR) NOT NULL,
    otp_hash           VARCHAR2(255 CHAR) NOT NULL,
    purpose            VARCHAR2(30 CHAR) NOT NULL,
    otp_status         VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    expires_at         TIMESTAMP(6) NOT NULL,
    verified_at        TIMESTAMP(6),
    failed_attempts    NUMBER(3) DEFAULT 0 NOT NULL,
    created_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_otp_verification PRIMARY KEY (otp_id),
    CONSTRAINT uq_otp_challenge_id UNIQUE (challenge_id),
    CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES app_user (user_id),
    CONSTRAINT ck_otp_purpose CHECK (purpose IN ('LOGIN', 'FUND_TRANSFER', 'BILL_PAYMENT', 'PASSWORD_RESET')),
    CONSTRAINT ck_otp_status CHECK (otp_status IN ('PENDING', 'VERIFIED', 'EXPIRED', 'FAILED')),
    CONSTRAINT ck_otp_failed_attempts CHECK (failed_attempts >= 0)
);

CREATE INDEX ix_otp_user_purpose_time ON otp_verification (user_id, purpose, created_at DESC);
