-- Beneficiaries, transfers, billers and bill payments.
-- Run after 10_transaction_status_history.sql, 10_notification_tables.sql, and 13_loan_payment_tables.sql as NET_BANKING_APP.
SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE biller (
    biller_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    biller_code VARCHAR2(40 CHAR) NOT NULL,
    biller_name VARCHAR2(200 CHAR) NOT NULL,
    category VARCHAR2(60 CHAR) NOT NULL,
    reference_label VARCHAR2(100 CHAR) NOT NULL,
    min_amount NUMBER(19,4) DEFAULT 1 NOT NULL,
    max_amount NUMBER(19,4) DEFAULT 100000 NOT NULL,
    is_active CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_biller PRIMARY KEY (biller_id),
    CONSTRAINT uq_biller_code UNIQUE (biller_code),
    CONSTRAINT ck_biller_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT ck_biller_amounts CHECK (min_amount > 0 AND max_amount >= min_amount)
);

CREATE TABLE fund_transfer (
    transfer_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    transaction_id NUMBER(19) NOT NULL,
    source_account_id NUMBER(19) NOT NULL,
    beneficiary_id NUMBER(19) NOT NULL,
    initiated_by_user_id NUMBER(19) NOT NULL,
    idempotency_key VARCHAR2(100 CHAR) NOT NULL,
    transfer_status VARCHAR2(20 CHAR) DEFAULT 'COMPLETED' NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_fund_transfer PRIMARY KEY (transfer_id),
    CONSTRAINT uq_transfer_idempotency UNIQUE (initiated_by_user_id, idempotency_key),
    CONSTRAINT uq_transfer_transaction UNIQUE (transaction_id),
    CONSTRAINT fk_transfer_tx FOREIGN KEY (transaction_id) REFERENCES bank_transaction(transaction_id),
    CONSTRAINT fk_transfer_source FOREIGN KEY (source_account_id) REFERENCES bank_account(account_id),
    CONSTRAINT fk_transfer_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES beneficiary(beneficiary_id),
    CONSTRAINT fk_transfer_user FOREIGN KEY (initiated_by_user_id) REFERENCES app_user(user_id),
    CONSTRAINT ck_transfer_status CHECK (transfer_status IN ('COMPLETED', 'FAILED'))
);

CREATE TABLE bill_payment (
    bill_payment_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    transaction_id NUMBER(19) NOT NULL,
    source_account_id NUMBER(19) NOT NULL,
    biller_id NUMBER(19) NOT NULL,
    initiated_by_user_id NUMBER(19) NOT NULL,
    bill_reference VARCHAR2(150 CHAR) NOT NULL,
    idempotency_key VARCHAR2(100 CHAR) NOT NULL,
    payment_status VARCHAR2(20 CHAR) DEFAULT 'COMPLETED' NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_bill_payment PRIMARY KEY (bill_payment_id),
    CONSTRAINT uq_bill_payment_idempotency UNIQUE (initiated_by_user_id, idempotency_key),
    CONSTRAINT uq_bill_payment_transaction UNIQUE (transaction_id),
    CONSTRAINT fk_bill_payment_tx FOREIGN KEY (transaction_id) REFERENCES bank_transaction(transaction_id),
    CONSTRAINT fk_bill_payment_source FOREIGN KEY (source_account_id) REFERENCES bank_account(account_id),
    CONSTRAINT fk_bill_payment_biller FOREIGN KEY (biller_id) REFERENCES biller(biller_id),
    CONSTRAINT fk_bill_payment_user FOREIGN KEY (initiated_by_user_id) REFERENCES app_user(user_id),
    CONSTRAINT ck_bill_payment_status CHECK (payment_status IN ('COMPLETED', 'FAILED'))
);

INSERT INTO biller (biller_code, biller_name, category, reference_label) VALUES ('ELECTRICITY', 'Demo Electricity Board', 'UTILITIES', 'Consumer number');
INSERT INTO biller (biller_code, biller_name, category, reference_label) VALUES ('MOBILE', 'Demo Mobile Services', 'TELECOM', 'Mobile number');
INSERT INTO biller (biller_code, biller_name, category, reference_label) VALUES ('WATER', 'Demo Water Authority', 'UTILITIES', 'Connection number');
COMMIT;
PROMPT Payment feature tables created successfully.
WHENEVER SQLERROR CONTINUE NONE
