-- Internet Net Banking Application
-- Security foundation: roles, application users, and role assignments
--
-- Run as NET_BANKING_APP while connected to FREEPDB1.
-- Run as a script (F5) in Oracle SQL Developer.
-- Do not run this script a second time after the tables exist.

SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE role (
    role_id        NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_code      VARCHAR2(50 CHAR)  NOT NULL,
    role_name      VARCHAR2(100 CHAR) NOT NULL,
    description    VARCHAR2(500 CHAR),
    is_active      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_role PRIMARY KEY (role_id),
    CONSTRAINT uq_role_code UNIQUE (role_code),
    CONSTRAINT uq_role_name UNIQUE (role_name),
    CONSTRAINT ck_role_is_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE app_user (
    user_id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username              VARCHAR2(100 CHAR) NOT NULL,
    email                 VARCHAR2(254 CHAR) NOT NULL,
    password_hash         VARCHAR2(255 CHAR) NOT NULL,
    account_status        VARCHAR2(30 CHAR) DEFAULT 'PENDING_VERIFICATION' NOT NULL,
    failed_login_attempts NUMBER(3) DEFAULT 0 NOT NULL,
    last_login_at         TIMESTAMP(6),
    password_changed_at   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    created_at            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_app_user PRIMARY KEY (user_id),
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT ck_app_user_status CHECK (
        account_status IN ('PENDING_VERIFICATION', 'ACTIVE', 'LOCKED', 'DISABLED')
    ),
    CONSTRAINT ck_app_user_failed_logins CHECK (failed_login_attempts >= 0)
);

CREATE TABLE user_role (
    user_id             NUMBER(19) NOT NULL,
    role_id             NUMBER(19) NOT NULL,
    assigned_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    assigned_by_user_id NUMBER(19),

    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id)
        REFERENCES app_user (user_id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id)
        REFERENCES role (role_id),
    CONSTRAINT fk_user_role_assigned_by FOREIGN KEY (assigned_by_user_id)
        REFERENCES app_user (user_id)
);

-- The primary key starts with USER_ID. This additional index supports role-to-user queries.
CREATE INDEX ix_user_role_role_id ON user_role (role_id);

-- Oracle stores only password hashes. Spring Security will create these hashes later.
-- These two roles are reference data needed by the first application release.
INSERT INTO role (role_code, role_name, description)
VALUES ('ADMIN', 'Administrator', 'Manages administrative banking operations.');

INSERT INTO role (role_code, role_name, description)
VALUES ('CUSTOMER', 'Customer', 'Uses Internet Net Banking services.');

COMMIT;

-- This trigger maintains the last-modified timestamp even when an update comes from a tool other than Spring Boot.
CREATE OR REPLACE TRIGGER trg_app_user_set_updated_at
BEFORE UPDATE ON app_user
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

PROMPT Security tables created successfully.

WHENEVER SQLERROR CONTINUE NONE
