-- Internet Net Banking Application
-- Customer profiles and customer addresses
--
-- Run as NET_BANKING_APP while connected to FREEPDB1.
-- Run as a script (Run -> Run Script or F5) in Oracle SQL Developer.
-- Do not run this script a second time after the tables exist.

SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE customer (
    customer_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id           NUMBER(19) NOT NULL,
    customer_number   VARCHAR2(20 CHAR) NOT NULL,
    first_name        VARCHAR2(100 CHAR) NOT NULL,
    middle_name       VARCHAR2(100 CHAR),
    last_name         VARCHAR2(100 CHAR) NOT NULL,
    date_of_birth     DATE NOT NULL,
    mobile_number     VARCHAR2(20 CHAR) NOT NULL,
    kyc_status        VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
    kyc_verified_at   TIMESTAMP(6),
    is_active         CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_customer PRIMARY KEY (customer_id),
    CONSTRAINT fk_customer_user FOREIGN KEY (user_id)
        REFERENCES app_user (user_id),
    CONSTRAINT uq_customer_user UNIQUE (user_id),
    CONSTRAINT uq_customer_number UNIQUE (customer_number),
    CONSTRAINT ck_customer_number_upper CHECK (customer_number = UPPER(customer_number)),
    CONSTRAINT ck_customer_kyc_status CHECK (
        kyc_status IN ('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED')
    ),
    CONSTRAINT ck_customer_kyc_time CHECK (
        (kyc_status = 'VERIFIED' AND kyc_verified_at IS NOT NULL)
        OR kyc_status <> 'VERIFIED'
    ),
    CONSTRAINT ck_customer_is_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE customer_address (
    customer_address_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id         NUMBER(19) NOT NULL,
    address_type        VARCHAR2(20 CHAR) NOT NULL,
    address_line_1      VARCHAR2(200 CHAR) NOT NULL,
    address_line_2      VARCHAR2(200 CHAR),
    city                VARCHAR2(100 CHAR) NOT NULL,
    state               VARCHAR2(100 CHAR) NOT NULL,
    postal_code         VARCHAR2(20 CHAR) NOT NULL,
    country_code        CHAR(2 CHAR) DEFAULT 'IN' NOT NULL,
    is_primary          CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_customer_address PRIMARY KEY (customer_address_id),
    CONSTRAINT fk_customer_address_customer FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id),
    CONSTRAINT uq_customer_address_type UNIQUE (customer_id, address_type),
    CONSTRAINT ck_customer_address_type CHECK (
        address_type IN ('RESIDENTIAL', 'MAILING', 'WORK')
    ),
    CONSTRAINT ck_customer_address_country CHECK (country_code = UPPER(country_code)),
    CONSTRAINT ck_customer_address_primary CHECK (is_primary IN ('Y', 'N'))
);

CREATE OR REPLACE TRIGGER trg_customer_set_updated_at
BEFORE UPDATE ON customer
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_customer_address_set_updated
BEFORE UPDATE ON customer_address
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

PROMPT Customer tables created successfully.

WHENEVER SQLERROR CONTINUE NONE
