-- Internet Net Banking Application
-- Bank accounts and account ownership
--
-- Run after 03_customer_tables.sql as NET_BANKING_APP on FREEPDB1.
-- Run as a script (Run -> Run Script or F5) in Oracle SQL Developer.
-- Do not run this script a second time after the tables exist.

SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE bank_account (
    account_id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    branch_id          NUMBER(19) NOT NULL,
    account_number     VARCHAR2(20 CHAR) NOT NULL,
    account_type       VARCHAR2(20 CHAR) NOT NULL,
    currency_code      CHAR(3 CHAR) DEFAULT 'INR' NOT NULL,
    account_status     VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    current_balance    NUMBER(19,4) DEFAULT 0 NOT NULL,
    available_balance  NUMBER(19,4) DEFAULT 0 NOT NULL,
    opened_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    closed_at          TIMESTAMP(6),
    created_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_bank_account PRIMARY KEY (account_id),
    CONSTRAINT fk_bank_account_branch FOREIGN KEY (branch_id)
        REFERENCES branch (branch_id),
    CONSTRAINT uq_bank_account_number UNIQUE (account_number),
    CONSTRAINT ck_bank_account_type CHECK (
        account_type IN ('SAVINGS', 'CURRENT')
    ),
    CONSTRAINT ck_bank_account_currency CHECK (currency_code = UPPER(currency_code)),
    CONSTRAINT ck_bank_account_status CHECK (
        account_status IN ('PENDING', 'ACTIVE', 'FROZEN', 'CLOSED')
    ),
    CONSTRAINT ck_bank_account_number CHECK (REGEXP_LIKE(account_number, '^[0-9]{10,20}$')),
    CONSTRAINT ck_bank_account_balances CHECK (
        current_balance >= 0
        AND available_balance >= 0
        AND available_balance <= current_balance
    ),
    CONSTRAINT ck_bank_account_closed CHECK (
        (account_status = 'CLOSED' AND closed_at IS NOT NULL)
        OR account_status <> 'CLOSED'
    )
);

CREATE TABLE account_holder (
    account_id       NUMBER(19) NOT NULL,
    customer_id      NUMBER(19) NOT NULL,
    holder_type      VARCHAR2(20 CHAR) DEFAULT 'PRIMARY' NOT NULL,
    is_active        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    joined_at        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_account_holder PRIMARY KEY (account_id, customer_id),
    CONSTRAINT fk_account_holder_account FOREIGN KEY (account_id)
        REFERENCES bank_account (account_id),
    CONSTRAINT fk_account_holder_customer FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id),
    CONSTRAINT ck_account_holder_type CHECK (
        holder_type IN ('PRIMARY', 'JOINT')
    ),
    CONSTRAINT ck_account_holder_active CHECK (is_active IN ('Y', 'N'))
);

-- The primary key starts with ACCOUNT_ID. This index supports customer-to-account queries.
CREATE INDEX ix_account_holder_customer ON account_holder (customer_id);

CREATE OR REPLACE TRIGGER trg_bank_account_set_updated_at
BEFORE UPDATE ON bank_account
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

PROMPT Account tables created successfully.

WHENEVER SQLERROR CONTINUE NONE
