-- Internet Net Banking Application
-- Customer transfer beneficiaries
--
-- Run after 03_customer_tables.sql as NET_BANKING_APP on FREEPDB1.
-- Run as a script (Run -> Run Script or F5) in Oracle SQL Developer.
-- Do not run this script a second time after the tables exist.

SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE beneficiary (
    beneficiary_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id         NUMBER(19) NOT NULL,
    nickname            VARCHAR2(100 CHAR) NOT NULL,
    beneficiary_name    VARCHAR2(200 CHAR) NOT NULL,
    account_number      VARCHAR2(20 CHAR) NOT NULL,
    ifsc_code           VARCHAR2(11 CHAR) NOT NULL,
    bank_name           VARCHAR2(200 CHAR) NOT NULL,
    beneficiary_status  VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    activated_at        TIMESTAMP(6),
    created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_beneficiary PRIMARY KEY (beneficiary_id),
    CONSTRAINT fk_beneficiary_customer FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id),
    CONSTRAINT uq_beneficiary_nickname UNIQUE (customer_id, nickname),
    CONSTRAINT uq_beneficiary_account UNIQUE (customer_id, account_number, ifsc_code),
    CONSTRAINT ck_beneficiary_account_number CHECK (
        REGEXP_LIKE(account_number, '^[0-9]{10,20}$')
    ),
    CONSTRAINT ck_beneficiary_ifsc_upper CHECK (ifsc_code = UPPER(ifsc_code)),
    CONSTRAINT ck_beneficiary_ifsc_format CHECK (
        REGEXP_LIKE(ifsc_code, '^[A-Z]{4}0[A-Z0-9]{6}$')
    ),
    CONSTRAINT ck_beneficiary_status CHECK (
        beneficiary_status IN ('PENDING', 'ACTIVE', 'DISABLED', 'REJECTED')
    ),
    CONSTRAINT ck_beneficiary_activated CHECK (
        (beneficiary_status = 'ACTIVE' AND activated_at IS NOT NULL)
        OR beneficiary_status <> 'ACTIVE'
    )
);

CREATE OR REPLACE TRIGGER trg_beneficiary_set_updated_at
BEFORE UPDATE ON beneficiary
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

PROMPT Beneficiary tables created successfully.

WHENEVER SQLERROR CONTINUE NONE
