-- Internet Net Banking Application
-- Immutable transaction lifecycle history.
--
-- Run after 06_transaction_tables.sql and 01_security_tables.sql.
-- Run as NET_BANKING_APP while connected to FREEPDB1.
-- Run as a script (Run -> Run Script or F5) in Oracle SQL Developer.
-- Do not run this script a second time after the table exists.

SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE bank_transaction_status_history (
    status_history_id   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    transaction_id      NUMBER(19) NOT NULL,
    previous_status     VARCHAR2(20 CHAR),
    new_status          VARCHAR2(20 CHAR) NOT NULL,
    failure_reason      VARCHAR2(500 CHAR),
    changed_by_user_id  NUMBER(19),
    changed_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_bank_txn_status_history PRIMARY KEY (status_history_id),
    CONSTRAINT fk_bank_txn_status_txn FOREIGN KEY (transaction_id)
        REFERENCES bank_transaction (transaction_id),
    CONSTRAINT fk_bank_txn_status_user FOREIGN KEY (changed_by_user_id)
        REFERENCES app_user (user_id),
    CONSTRAINT ck_bank_txn_previous_status CHECK (
        previous_status IS NULL
        OR previous_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED')
    ),
    CONSTRAINT ck_bank_txn_new_status CHECK (
        new_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REVERSED')
    ),
    CONSTRAINT ck_bank_txn_status_changed CHECK (
        previous_status IS NULL OR previous_status <> new_status
    ),
    CONSTRAINT ck_bank_txn_failure_reason CHECK (
        (new_status = 'FAILED' AND failure_reason IS NOT NULL)
        OR (new_status <> 'FAILED' AND failure_reason IS NULL)
    )
);

CREATE INDEX ix_bank_txn_status_history
    ON bank_transaction_status_history (transaction_id, changed_at, status_history_id);

PROMPT Transaction status history created successfully.

WHENEVER SQLERROR CONTINUE NONE
