-- Tokenized card records and customer card controls.
-- Run as NET_BANKING_APP after 04_account_tables.sql.
SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE bank_card (
    card_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id   NUMBER(19) NOT NULL,
    account_id    NUMBER(19) NOT NULL,
    card_token    VARCHAR2(128 CHAR) NOT NULL,
    last_four     CHAR(4 CHAR) NOT NULL,
    card_type     VARCHAR2(10 CHAR) NOT NULL,
    card_network  VARCHAR2(20 CHAR) NOT NULL,
    expiry_month  NUMBER(2) NOT NULL,
    expiry_year   NUMBER(4) NOT NULL,
    card_status   VARCHAR2(20 CHAR) DEFAULT 'INACTIVE' NOT NULL,
    issued_at     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    activated_at  TIMESTAMP(6),
    updated_at    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_bank_card PRIMARY KEY (card_id),
    CONSTRAINT fk_bank_card_customer FOREIGN KEY (customer_id) REFERENCES customer (customer_id),
    CONSTRAINT fk_bank_card_account FOREIGN KEY (account_id) REFERENCES bank_account (account_id),
    CONSTRAINT fk_bank_card_holder FOREIGN KEY (account_id, customer_id)
        REFERENCES account_holder (account_id, customer_id),
    CONSTRAINT uq_bank_card_token UNIQUE (card_token),
    CONSTRAINT ck_bank_card_last_four CHECK (REGEXP_LIKE(last_four, '^[0-9]{4}$')),
    CONSTRAINT ck_bank_card_type CHECK (card_type IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ck_bank_card_network CHECK (card_network IN ('VISA', 'MASTERCARD', 'RUPAY')),
    CONSTRAINT ck_bank_card_expiry_month CHECK (expiry_month BETWEEN 1 AND 12),
    CONSTRAINT ck_bank_card_status CHECK (card_status IN ('INACTIVE', 'ACTIVE', 'BLOCKED', 'EXPIRED', 'CLOSED')),
    CONSTRAINT ck_bank_card_activation CHECK (
        (card_status = 'INACTIVE' AND activated_at IS NULL) OR card_status <> 'INACTIVE'
    )
);

CREATE INDEX ix_bank_card_customer ON bank_card (customer_id, card_id);
CREATE INDEX ix_bank_card_account ON bank_card (account_id);

CREATE OR REPLACE TRIGGER trg_bank_card_set_updated_at
BEFORE UPDATE ON bank_card
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

PROMPT Card tables created successfully.
WHENEVER SQLERROR CONTINUE NONE
