-- Customer loan accounts and repayment schedules.
-- Run as NET_BANKING_APP after 03_customer_tables.sql.
SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE loan_account (
    loan_id                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id            NUMBER(19) NOT NULL,
    loan_account_number    VARCHAR2(24 CHAR) NOT NULL,
    loan_type              VARCHAR2(20 CHAR) NOT NULL,
    principal_amount       NUMBER(19,4) NOT NULL,
    outstanding_principal  NUMBER(19,4) NOT NULL,
    interest_rate          NUMBER(7,4) NOT NULL,
    term_months            NUMBER(4) NOT NULL,
    emi_amount             NUMBER(19,4) NOT NULL,
    currency_code          CHAR(3 CHAR) DEFAULT 'INR' NOT NULL,
    disbursed_on           DATE NOT NULL,
    next_due_date          DATE,
    maturity_date          DATE NOT NULL,
    loan_status            VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    created_at             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_loan_account PRIMARY KEY (loan_id),
    CONSTRAINT fk_loan_customer FOREIGN KEY (customer_id) REFERENCES customer (customer_id),
    CONSTRAINT uq_loan_account_number UNIQUE (loan_account_number),
    CONSTRAINT ck_loan_account_number CHECK (REGEXP_LIKE(loan_account_number, '^[A-Z0-9]{8,24}$')),
    CONSTRAINT ck_loan_type CHECK (loan_type IN ('HOME', 'PERSONAL', 'VEHICLE', 'EDUCATION')),
    CONSTRAINT ck_loan_principal CHECK (principal_amount > 0),
    CONSTRAINT ck_loan_outstanding CHECK (
        outstanding_principal >= 0 AND outstanding_principal <= principal_amount
    ),
    CONSTRAINT ck_loan_interest CHECK (interest_rate >= 0 AND interest_rate <= 100),
    CONSTRAINT ck_loan_term CHECK (term_months > 0),
    CONSTRAINT ck_loan_emi CHECK (emi_amount > 0),
    CONSTRAINT ck_loan_currency CHECK (currency_code = UPPER(currency_code)),
    CONSTRAINT ck_loan_dates CHECK (maturity_date >= disbursed_on),
    CONSTRAINT ck_loan_status CHECK (loan_status IN ('PENDING', 'ACTIVE', 'PAID_OFF', 'DEFAULTED', 'CLOSED')),
    CONSTRAINT ck_loan_due_date CHECK (
        (loan_status = 'ACTIVE' AND next_due_date IS NOT NULL)
        OR (loan_status IN ('PAID_OFF', 'CLOSED') AND next_due_date IS NULL)
        OR loan_status IN ('PENDING', 'DEFAULTED')
    )
);

CREATE INDEX ix_loan_customer ON loan_account (customer_id, loan_id);

CREATE OR REPLACE TRIGGER trg_loan_set_updated_at
BEFORE UPDATE ON loan_account
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

PROMPT Loan tables created successfully.
WHENEVER SQLERROR CONTINUE NONE
