-- Atomic customer loan payments linked to the banking transaction ledger.
-- Run as NET_BANKING_APP after 06_transaction_tables.sql, 07_audit_security_tables.sql,
-- 10_transaction_status_history.sql, and 12_loan_tables.sql.
SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER TABLE bank_transaction DROP CONSTRAINT ck_bank_txn_type;
ALTER TABLE bank_transaction ADD CONSTRAINT ck_bank_txn_type CHECK (
    transaction_type IN ('TRANSFER', 'DEPOSIT', 'WITHDRAWAL', 'LOAN_PAYMENT', 'REVERSAL')
);

CREATE TABLE loan_payment (
    loan_payment_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    loan_id               NUMBER(19) NOT NULL,
    source_account_id     NUMBER(19) NOT NULL,
    transaction_id        NUMBER(19) NOT NULL,
    transaction_reference VARCHAR2(50 CHAR) NOT NULL,
    idempotency_key       VARCHAR2(64 CHAR) NOT NULL,
    amount                NUMBER(19,4) NOT NULL,
    currency_code         CHAR(3 CHAR) NOT NULL,
    outstanding_after     NUMBER(19,4) NOT NULL,
    payment_status        VARCHAR2(20 CHAR) DEFAULT 'COMPLETED' NOT NULL,
    paid_at               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_loan_payment PRIMARY KEY (loan_payment_id),
    CONSTRAINT fk_loan_payment_loan FOREIGN KEY (loan_id) REFERENCES loan_account (loan_id),
    CONSTRAINT fk_loan_payment_account FOREIGN KEY (source_account_id) REFERENCES bank_account (account_id),
    CONSTRAINT fk_loan_payment_transaction FOREIGN KEY (transaction_id) REFERENCES bank_transaction (transaction_id),
    CONSTRAINT uq_loan_payment_transaction UNIQUE (transaction_id),
    CONSTRAINT uq_loan_payment_reference UNIQUE (transaction_reference),
    CONSTRAINT uq_loan_payment_idempotency UNIQUE (loan_id, idempotency_key),
    CONSTRAINT ck_loan_payment_amount CHECK (amount > 0),
    CONSTRAINT ck_loan_payment_currency CHECK (currency_code = UPPER(currency_code)),
    CONSTRAINT ck_loan_payment_outstanding CHECK (outstanding_after >= 0),
    CONSTRAINT ck_loan_payment_status CHECK (payment_status = 'COMPLETED')
);

CREATE INDEX ix_loan_payment_history ON loan_payment (loan_id, paid_at, loan_payment_id);
CREATE INDEX ix_loan_payment_source ON loan_payment (source_account_id, paid_at);

PROMPT Loan payment tables created successfully.
WHENEVER SQLERROR CONTINUE NONE
