CREATE TABLE role (
    role_id        NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_code      VARCHAR2(50 CHAR)  NOT NULL,
    role_name      VARCHAR2(100 CHAR) NOT NULL,
    description    VARCHAR2(500 CHAR),
    is_active      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_role PRIMARY KEY (role_id),
    CONSTRAINT uq_role_code UNIQUE (role_code),
    CONSTRAINT uq_role_name UNIQUE (role_name),
    CONSTRAINT ck_role_is_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE app_user (
    user_id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username              VARCHAR2(100 CHAR) NOT NULL,
    email                 VARCHAR2(254 CHAR) NOT NULL,
    password_hash         VARCHAR2(255 CHAR) NOT NULL,
    account_status        VARCHAR2(30 CHAR) DEFAULT 'PENDING_VERIFICATION' NOT NULL,
    failed_login_attempts NUMBER(3) DEFAULT 0 NOT NULL,
    last_login_at         TIMESTAMP(6),
    password_changed_at   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    created_at            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_app_user PRIMARY KEY (user_id),
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT ck_app_user_status CHECK (
        account_status IN ('PENDING_VERIFICATION', 'ACTIVE', 'LOCKED', 'DISABLED')
    ),
    CONSTRAINT ck_app_user_failed_logins CHECK (failed_login_attempts >= 0)
);

CREATE TABLE user_role (
    user_id             NUMBER(19) NOT NULL,
    role_id             NUMBER(19) NOT NULL,
    assigned_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    assigned_by_user_id NUMBER(19),

    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id)
        REFERENCES app_user (user_id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id)
        REFERENCES role (role_id),
    CONSTRAINT fk_user_role_assigned_by FOREIGN KEY (assigned_by_user_id)
        REFERENCES app_user (user_id)
);

CREATE INDEX ix_user_role_role_id ON user_role (role_id);

INSERT INTO role (role_code, role_name, description)
VALUES ('ADMIN', 'Administrator', 'Manages administrative banking operations.');

INSERT INTO role (role_code, role_name, description)
VALUES ('CUSTOMER', 'Customer', 'Uses Internet Net Banking services.');


CREATE OR REPLACE TRIGGER trg_app_user_set_updated_at
BEFORE UPDATE ON app_user
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE customer (
    customer_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id           NUMBER(19) NOT NULL,
    customer_number   VARCHAR2(20 CHAR) NOT NULL,
    first_name        VARCHAR2(100 CHAR) NOT NULL,
    middle_name       VARCHAR2(100 CHAR),
    last_name         VARCHAR2(100 CHAR) NOT NULL,
    date_of_birth     DATE NOT NULL,
    mobile_number     VARCHAR2(20 CHAR) NOT NULL,
    kyc_status        VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
    kyc_verified_at   TIMESTAMP(6),
    is_active         CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_customer PRIMARY KEY (customer_id),
    CONSTRAINT fk_customer_user FOREIGN KEY (user_id)
        REFERENCES app_user (user_id),
    CONSTRAINT uq_customer_user UNIQUE (user_id),
    CONSTRAINT uq_customer_number UNIQUE (customer_number),
    CONSTRAINT ck_customer_number_upper CHECK (customer_number = UPPER(customer_number)),
    CONSTRAINT ck_customer_kyc_status CHECK (
        kyc_status IN ('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED')
    ),
    CONSTRAINT ck_customer_kyc_time CHECK (
        (kyc_status = 'VERIFIED' AND kyc_verified_at IS NOT NULL)
        OR kyc_status <> 'VERIFIED'
    ),
    CONSTRAINT ck_customer_is_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE customer_address (
    customer_address_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id         NUMBER(19) NOT NULL,
    address_type        VARCHAR2(20 CHAR) NOT NULL,
    address_line_1      VARCHAR2(200 CHAR) NOT NULL,
    address_line_2      VARCHAR2(200 CHAR),
    city                VARCHAR2(100 CHAR) NOT NULL,
    state               VARCHAR2(100 CHAR) NOT NULL,
    postal_code         VARCHAR2(20 CHAR) NOT NULL,
    country_code        CHAR(2 CHAR) DEFAULT 'IN' NOT NULL,
    is_primary          CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_customer_address PRIMARY KEY (customer_address_id),
    CONSTRAINT fk_customer_address_customer FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id),
    CONSTRAINT uq_customer_address_type UNIQUE (customer_id, address_type),
    CONSTRAINT ck_customer_address_type CHECK (
        address_type IN ('RESIDENTIAL', 'MAILING', 'WORK')
    ),
    CONSTRAINT ck_customer_address_country CHECK (country_code = UPPER(country_code)),
    CONSTRAINT ck_customer_address_primary CHECK (is_primary IN ('Y', 'N'))
);

CREATE OR REPLACE TRIGGER trg_customer_set_updated_at
BEFORE UPDATE ON customer
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_customer_address_set_updated
BEFORE UPDATE ON customer_address
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE login_audit (
    login_audit_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id             NUMBER(19),
    username_attempted  VARCHAR2(100 CHAR) NOT NULL,
    login_outcome       VARCHAR2(20 CHAR) NOT NULL,
    failure_reason      VARCHAR2(200 CHAR),
    client_ip_address   VARCHAR2(45 CHAR),
    user_agent          VARCHAR2(500 CHAR),
    occurred_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_login_audit PRIMARY KEY (login_audit_id),
    CONSTRAINT fk_login_audit_user FOREIGN KEY (user_id)
        REFERENCES app_user (user_id),
    CONSTRAINT ck_login_audit_outcome CHECK (login_outcome IN ('SUCCESS', 'FAILURE'))
);

ALTER TABLE app_user ADD (
    locked_until TIMESTAMP(6)
);

CREATE TABLE otp_verification (
    otp_id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id            NUMBER(19) NOT NULL,
    challenge_id       VARCHAR2(100 CHAR) NOT NULL,
    otp_hash           VARCHAR2(255 CHAR) NOT NULL,
    purpose            VARCHAR2(30 CHAR) NOT NULL,
    otp_status         VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    expires_at         TIMESTAMP(6) NOT NULL,
    verified_at        TIMESTAMP(6),
    failed_attempts    NUMBER(3) DEFAULT 0 NOT NULL,
    created_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_otp_verification PRIMARY KEY (otp_id),
    CONSTRAINT uq_otp_challenge_id UNIQUE (challenge_id),
    CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES app_user (user_id),
    CONSTRAINT ck_otp_purpose CHECK (purpose IN ('LOGIN', 'FUND_TRANSFER', 'BILL_PAYMENT', 'PASSWORD_RESET')),
    CONSTRAINT ck_otp_status CHECK (otp_status IN ('PENDING', 'VERIFIED', 'EXPIRED', 'FAILED')),
    CONSTRAINT ck_otp_failed_attempts CHECK (failed_attempts >= 0)
);

CREATE INDEX ix_otp_user_purpose_time ON otp_verification (user_id, purpose, created_at DESC);

CREATE TABLE user_totp (
    user_id            NUMBER(19) NOT NULL,
    secret_ciphertext  VARCHAR2(2048 CHAR) NOT NULL,
    is_enabled         CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    confirmed_at       TIMESTAMP(6),
    created_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_user_totp PRIMARY KEY (user_id),
    CONSTRAINT fk_user_totp_user FOREIGN KEY (user_id) REFERENCES app_user (user_id),
    CONSTRAINT ck_user_totp_enabled CHECK (is_enabled IN ('Y', 'N'))
);

CREATE OR REPLACE TRIGGER trg_user_totp_set_updated_at
BEFORE UPDATE ON user_totp
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

ALTER TABLE user_totp ADD (last_used_time_step NUMBER(19));

CREATE UNIQUE INDEX uq_app_user_username_ci ON app_user (LOWER(username));
CREATE UNIQUE INDEX uq_app_user_email_ci ON app_user (LOWER(email));
ALTER TABLE otp_verification ADD (intent_digest VARCHAR2(64 CHAR), version NUMBER(19) DEFAULT 0 NOT NULL);
ALTER TABLE otp_verification DROP CONSTRAINT ck_otp_purpose;
ALTER TABLE otp_verification ADD CONSTRAINT ck_otp_purpose CHECK (purpose IN ('LOGIN','FUND_TRANSFER','BILL_PAYMENT','BENEFICIARY_ACTIVATION','PASSWORD_RESET'));
CREATE INDEX ix_otp_intent ON otp_verification(user_id,purpose,otp_status,created_at);
CREATE TABLE otp_authorization (
    caller VARCHAR2(50 CHAR) NOT NULL,
    operation_id VARCHAR2(64 CHAR) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    purpose VARCHAR2(30 CHAR) NOT NULL,
    intent_digest VARCHAR2(64 CHAR) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_otp_authorization PRIMARY KEY(caller,operation_id),
    CONSTRAINT fk_otp_authorization_user FOREIGN KEY(user_id) REFERENCES app_user(user_id)
);
