CREATE TABLE bank_card (
    card_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id   NUMBER(19) NOT NULL,
    account_id    NUMBER(19) NOT NULL,
    card_token    VARCHAR2(128 CHAR) NOT NULL,
    last_four     CHAR(4 CHAR) NOT NULL,
    card_type     VARCHAR2(10 CHAR) NOT NULL,
    card_network  VARCHAR2(20 CHAR) NOT NULL,
    expiry_month  NUMBER(2) NOT NULL,
    expiry_year   NUMBER(4) NOT NULL,
    card_status   VARCHAR2(20 CHAR) DEFAULT 'INACTIVE' NOT NULL,
    issued_at     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    activated_at  TIMESTAMP(6),
    updated_at    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_bank_card PRIMARY KEY (card_id),
    CONSTRAINT uq_bank_card_token UNIQUE (card_token),
    CONSTRAINT ck_bank_card_last_four CHECK (REGEXP_LIKE(last_four, '^[0-9]{4}$')),
    CONSTRAINT ck_bank_card_type CHECK (card_type IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ck_bank_card_network CHECK (card_network IN ('VISA', 'MASTERCARD', 'RUPAY')),
    CONSTRAINT ck_bank_card_expiry_month CHECK (expiry_month BETWEEN 1 AND 12),
    CONSTRAINT ck_bank_card_status CHECK (card_status IN ('INACTIVE', 'ACTIVE', 'BLOCKED', 'EXPIRED', 'CLOSED')),
    CONSTRAINT ck_bank_card_activation CHECK (
        (card_status = 'INACTIVE' AND activated_at IS NULL) OR card_status <> 'INACTIVE'
    )
);

CREATE INDEX ix_bank_card_customer ON bank_card (customer_id, card_id);
CREATE INDEX ix_bank_card_account ON bank_card (account_id);

CREATE OR REPLACE TRIGGER trg_bank_card_set_updated_at
BEFORE UPDATE ON bank_card
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE loan_account (
    loan_id                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id            NUMBER(19) NOT NULL,
    loan_account_number    VARCHAR2(24 CHAR) NOT NULL,
    loan_type              VARCHAR2(20 CHAR) NOT NULL,
    principal_amount       NUMBER(19,4) NOT NULL,
    outstanding_principal  NUMBER(19,4) NOT NULL,
    interest_rate          NUMBER(7,4) NOT NULL,
    term_months            NUMBER(4) NOT NULL,
    emi_amount             NUMBER(19,4) NOT NULL,
    currency_code          CHAR(3 CHAR) DEFAULT 'INR' NOT NULL,
    disbursed_on           DATE NOT NULL,
    next_due_date          DATE,
    maturity_date          DATE NOT NULL,
    loan_status            VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    created_at             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_loan_account PRIMARY KEY (loan_id),
    CONSTRAINT uq_loan_account_number UNIQUE (loan_account_number),
    CONSTRAINT ck_loan_account_number CHECK (REGEXP_LIKE(loan_account_number, '^[A-Z0-9]{8,24}$')),
    CONSTRAINT ck_loan_type CHECK (loan_type IN ('HOME', 'PERSONAL', 'VEHICLE', 'EDUCATION')),
    CONSTRAINT ck_loan_principal CHECK (principal_amount > 0),
    CONSTRAINT ck_loan_outstanding CHECK (
        outstanding_principal >= 0 AND outstanding_principal <= principal_amount
    ),
    CONSTRAINT ck_loan_interest CHECK (interest_rate >= 0 AND interest_rate <= 100),
    CONSTRAINT ck_loan_term CHECK (term_months > 0),
    CONSTRAINT ck_loan_emi CHECK (emi_amount > 0),
    CONSTRAINT ck_loan_currency CHECK (currency_code = UPPER(currency_code)),
    CONSTRAINT ck_loan_dates CHECK (maturity_date >= disbursed_on),
    CONSTRAINT ck_loan_status CHECK (loan_status IN ('PENDING', 'ACTIVE', 'PAID_OFF', 'DEFAULTED', 'CLOSED')),
    CONSTRAINT ck_loan_due_date CHECK (
        (loan_status = 'ACTIVE' AND next_due_date IS NOT NULL)
        OR (loan_status IN ('PAID_OFF', 'CLOSED') AND next_due_date IS NULL)
        OR loan_status IN ('PENDING', 'DEFAULTED')
    )
);

CREATE INDEX ix_loan_customer ON loan_account (customer_id, loan_id);

CREATE OR REPLACE TRIGGER trg_loan_set_updated_at
BEFORE UPDATE ON loan_account
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE loan_payment (
    loan_payment_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    loan_id               NUMBER(19) NOT NULL,
    source_account_id     NUMBER(19) NOT NULL,
    transaction_id        NUMBER(19) NOT NULL,
    transaction_reference VARCHAR2(50 CHAR) NOT NULL,
    idempotency_key       VARCHAR2(64 CHAR) NOT NULL,
    amount                NUMBER(19,4) NOT NULL,
    currency_code         CHAR(3 CHAR) NOT NULL,
    outstanding_after     NUMBER(19,4) NOT NULL,
    payment_status        VARCHAR2(20 CHAR) DEFAULT 'COMPLETED' NOT NULL,
    paid_at               TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_loan_payment PRIMARY KEY (loan_payment_id),
    CONSTRAINT fk_loan_payment_loan FOREIGN KEY (loan_id) REFERENCES loan_account (loan_id),
    CONSTRAINT uq_loan_payment_transaction UNIQUE (transaction_id),
    CONSTRAINT uq_loan_payment_reference UNIQUE (transaction_reference),
    CONSTRAINT uq_loan_payment_idempotency UNIQUE (loan_id, idempotency_key),
    CONSTRAINT ck_loan_payment_amount CHECK (amount > 0),
    CONSTRAINT ck_loan_payment_currency CHECK (currency_code = UPPER(currency_code)),
    CONSTRAINT ck_loan_payment_outstanding CHECK (outstanding_after >= 0),
    CONSTRAINT ck_loan_payment_status CHECK (payment_status = 'COMPLETED')
);

ALTER TABLE loan_payment ADD (
    request_fingerprint VARCHAR2(64 CHAR)
);
CREATE INDEX ix_loan_payment_history ON loan_payment(loan_id,paid_at,loan_payment_id);
CREATE TABLE loan_repayment_operation (
    operation_key VARCHAR2(64 CHAR) PRIMARY KEY,
    loan_id NUMBER(19) NOT NULL REFERENCES loan_account(loan_id),
    customer_id NUMBER(19) NOT NULL,
    request_key VARCHAR2(64 CHAR) NOT NULL,
    request_fingerprint VARCHAR2(64 CHAR) NOT NULL,
    amount NUMBER(19,4) NOT NULL CHECK(amount > 0),
    ledger_command CLOB NOT NULL,
    state VARCHAR2(20 CHAR) NOT NULL CHECK(state IN ('RESERVED','COMPLETED','FAILED')),
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_loan_repayment_request UNIQUE(loan_id,request_key)
);
CREATE INDEX ix_repayment_recovery ON loan_repayment_operation(state,created_at);
