-- Card number reveal, card PINs and credit-card billing.
-- The full card number is stored only as AES-GCM ciphertext bound to the card token; CVV is never stored.
-- The PIN is stored only as a BCrypt hash; failed attempts lock it for a configured period.
ALTER TABLE bank_card ADD (
    pan_ciphertext        VARCHAR2(256 CHAR),
    pin_hash              VARCHAR2(100 CHAR),
    pin_set_at            TIMESTAMP(6),
    pin_failed_attempts   NUMBER(2) DEFAULT 0 NOT NULL,
    pin_locked_until      TIMESTAMP(6),
    credit_limit          NUMBER(19,4),
    outstanding_balance   NUMBER(19,4),
    statement_balance     NUMBER(19,4),
    minimum_due           NUMBER(19,4),
    statement_date        DATE,
    payment_due_date      DATE,
    CONSTRAINT ck_bank_card_pin_attempts CHECK (pin_failed_attempts BETWEEN 0 AND 10),
    CONSTRAINT ck_bank_card_credit CHECK (
        (card_type = 'DEBIT' AND credit_limit IS NULL)
        OR (card_type = 'CREDIT' AND (credit_limit IS NULL OR (
            credit_limit > 0
            AND outstanding_balance >= 0
            AND statement_balance >= 0
            AND minimum_due >= 0
            AND minimum_due <= statement_balance
            AND statement_date IS NOT NULL
            AND payment_due_date >= statement_date)))
    )
);

CREATE TABLE card_transaction (
    card_transaction_id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    card_id                NUMBER(19) NOT NULL,
    transaction_reference  VARCHAR2(30 CHAR) NOT NULL,
    merchant_name          VARCHAR2(100 CHAR) NOT NULL,
    merchant_category      VARCHAR2(40 CHAR) NOT NULL,
    transaction_type       VARCHAR2(20 CHAR) NOT NULL,
    amount                 NUMBER(19,4) NOT NULL,
    currency_code          VARCHAR2(3 CHAR) DEFAULT 'INR' NOT NULL,
    transaction_status     VARCHAR2(20 CHAR) NOT NULL,
    posted_at              TIMESTAMP(6) NOT NULL,
    billed_on              DATE,

    CONSTRAINT pk_card_transaction PRIMARY KEY (card_transaction_id),
    CONSTRAINT fk_card_transaction_card FOREIGN KEY (card_id) REFERENCES bank_card (card_id),
    CONSTRAINT uq_card_transaction_reference UNIQUE (transaction_reference),
    CONSTRAINT ck_card_transaction_type CHECK (transaction_type IN ('PURCHASE', 'REFUND', 'PAYMENT')),
    CONSTRAINT ck_card_transaction_status CHECK (
        transaction_status IN ('PENDING', 'POSTED', 'CONVERTED_TO_EMI', 'DECLINED')
    ),
    CONSTRAINT ck_card_transaction_amount CHECK (amount > 0),
    CONSTRAINT ck_card_transaction_currency CHECK (REGEXP_LIKE(currency_code, '^[A-Z]{3}$'))
);

CREATE INDEX ix_card_transaction_card ON card_transaction (card_id, posted_at DESC, card_transaction_id DESC);

CREATE TABLE card_emi_plan (
    emi_plan_id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    card_id                NUMBER(19) NOT NULL,
    card_transaction_id    NUMBER(19) NOT NULL,
    request_key            VARCHAR2(64 CHAR) NOT NULL,
    principal_amount       NUMBER(19,4) NOT NULL,
    tenure_months          NUMBER(2) NOT NULL,
    annual_interest_rate   NUMBER(7,4) NOT NULL,
    monthly_instalment     NUMBER(19,4) NOT NULL,
    total_interest         NUMBER(19,4) NOT NULL,
    total_payable          NUMBER(19,4) NOT NULL,
    instalments_paid       NUMBER(2) DEFAULT 0 NOT NULL,
    first_due_date         DATE NOT NULL,
    plan_status            VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    created_at             TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_card_emi_plan PRIMARY KEY (emi_plan_id),
    CONSTRAINT fk_card_emi_plan_card FOREIGN KEY (card_id) REFERENCES bank_card (card_id),
    CONSTRAINT fk_card_emi_plan_transaction FOREIGN KEY (card_transaction_id)
        REFERENCES card_transaction (card_transaction_id),
    CONSTRAINT uq_card_emi_plan_transaction UNIQUE (card_transaction_id),
    CONSTRAINT uq_card_emi_plan_request UNIQUE (card_id, request_key),
    CONSTRAINT ck_card_emi_plan_tenure CHECK (tenure_months IN (3, 6, 9)),
    CONSTRAINT ck_card_emi_plan_amounts CHECK (
        principal_amount > 0 AND monthly_instalment > 0 AND total_interest >= 0
        AND total_payable >= principal_amount
    ),
    CONSTRAINT ck_card_emi_plan_paid CHECK (instalments_paid BETWEEN 0 AND tenure_months),
    CONSTRAINT ck_card_emi_plan_status CHECK (plan_status IN ('ACTIVE', 'CLOSED'))
);

CREATE INDEX ix_card_emi_plan_card ON card_emi_plan (card_id, emi_plan_id);
