spring.application.name=net-banking-backend
spring.profiles.default=local
server.error.include-message=never
app.security.max-failed-login-attempts=5
app.security.account-lock-minutes=15
app.security.jwt.expiration-minutes=30
app.security.cors.allowed-origins=http://localhost:8000,http://localhost:8080,http://localhost:4200
