spring.application.name=audit-reporting-service
server.port=${SERVER_PORT:8086}
spring.config.import=classpath:runtime.properties
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@//127.0.0.1:1521/FREEPDB1}
spring.datasource.username=${DB_USERNAME:NB_AUDIT}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.user=${MIGRATION_USERNAME:${spring.datasource.username}}
spring.flyway.password=${MIGRATION_PASSWORD:${spring.datasource.password}}
app.events.enabled=true
spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type=TIMESTAMP
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
