package com.netbanking.forex.service;

import static org.assertj.core.api.Assertions.*;

import com.netbanking.ServiceTestBase;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.netbanking.contracts.ForexLedgerReceipt;
import com.netbanking.forex.api.ForexQuoteResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.ZoneOffset;

class ForexStoreIntegrationTest extends ServiceTestBase {
    @Autowired JdbcTemplate jdbc;
    @Autowired ForexStore store;
    @Autowired ObjectMapper json;

    @BeforeEach
    void tables() {
        jdbc.execute("CREATE TABLE IF NOT EXISTS forex_quote (quote_id VARCHAR(36) PRIMARY KEY,"
                + "user_id BIGINT,source_account_id BIGINT,destination_account_id BIGINT,"
                + "source_currency CHAR(3),destination_currency CHAR(3),source_amount DECIMAL(19,4),"
                + "destination_amount DECIMAL(19,4),exchange_rate DECIMAL(19,8),created_at TIMESTAMP,expires_at TIMESTAMP)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS forex_conversion (conversion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                + "quote_id VARCHAR(36) UNIQUE,user_id BIGINT,request_key VARCHAR(64),request_fingerprint VARCHAR(64),"
                + "operation_id VARCHAR(36) UNIQUE,state VARCHAR(20),debit_transaction_id BIGINT,debit_reference VARCHAR(50),"
                + "credit_transaction_id BIGINT,credit_reference VARCHAR(50),created_at TIMESTAMP,next_attempt_at TIMESTAMP,"
                + "UNIQUE(user_id,request_key))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS event_outbox(event_id VARCHAR(36) PRIMARY KEY,destination VARCHAR(50),envelope CLOB)");
        jdbc.update("DELETE FROM forex_conversion");
        jdbc.update("DELETE FROM forex_quote");
        jdbc.update("DELETE FROM event_outbox");
    }

    @Test
    void reservesQuoteOnceAndCompletesWithTwoLedgerReferences() {
        LocalDateTime now = LocalDateTime.now(ZoneOffset.UTC);
        var quote = store.saveQuote(new ForexStore.Quote(new ForexQuoteResponse("quote-1", 10L, 20L,
                "INR", "USD", new BigDecimal("850"), new BigDecimal("10"),
                new BigDecimal("0.01176471"), "DEMO_CONFIGURED", now.plusMinutes(2).atOffset(ZoneOffset.UTC)), 7L, now));
        assertThat(store.quote(7L, "quote-1").response().exchangeRate())
                .isEqualByComparingTo("0.01176471");
        assertThat(store.quote(7L, "quote-1").response().expiresAt().getOffset())
                .isEqualTo(ZoneOffset.UTC);
        assertThat(json.valueToTree(store.quote(7L, "quote-1").response())
                .get("expiresAt").asText()).endsWith("Z");
        assertThatThrownBy(() -> store.quote(8L, "quote-1"))
                .isInstanceOf(com.netbanking.common.exception.ResourceNotFoundException.class);

        var operation = store.create(quote, "request-1", "a".repeat(64), "operation-1");
        assertThat(operation.state()).isEqualTo("AWAITING_OTP");
        store.authorized("operation-1");
        assertThat(store.recoverable()).hasSize(1);
        var receipt = new ForexLedgerReceipt(1L, "DR-1", 2L, "CR-1",
                new BigDecimal("850"), new BigDecimal("10"));
        var completed = store.complete("operation-1", receipt);
        assertThat(completed.status()).isEqualTo("COMPLETED");
        assertThat(completed.creditReference()).isEqualTo("CR-1");
        assertThat(store.complete("operation-1", receipt)).isEqualTo(completed);
        assertThat(store.recoverable()).isEmpty();
        assertThat(store.history(7L, 0, 20).getTotalElements()).isEqualTo(1);
        assertThat(store.history(8L, 0, 20).getTotalElements()).isZero();
        assertThatThrownBy(() -> store.create(quote, "request-2", "b".repeat(64), "operation-2"))
                .isInstanceOf(org.springframework.dao.DataIntegrityViolationException.class);
    }
}
