CREATE TABLE audit_event (
    audit_event_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id             NUMBER(19),
    event_type          VARCHAR2(100 CHAR) NOT NULL,
    entity_type         VARCHAR2(100 CHAR),
    entity_id           VARCHAR2(100 CHAR),
    outcome             VARCHAR2(20 CHAR) DEFAULT 'SUCCESS' NOT NULL,
    request_id          VARCHAR2(100 CHAR),
    client_ip_address   VARCHAR2(45 CHAR),
    event_details       CLOB,
    occurred_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_audit_event PRIMARY KEY (audit_event_id),
    CONSTRAINT ck_audit_event_outcome CHECK (
        outcome IN ('SUCCESS', 'FAILURE', 'DENIED')
    )
);
CREATE INDEX ix_audit_user_time ON audit_event(user_id,occurred_at);
CREATE INDEX ix_audit_entity ON audit_event(entity_type,entity_id);
