CREATE TABLE beneficiary (
    beneficiary_id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id         NUMBER(19) NOT NULL,
    nickname            VARCHAR2(100 CHAR) NOT NULL,
    beneficiary_name    VARCHAR2(200 CHAR) NOT NULL,
    account_number      VARCHAR2(20 CHAR) NOT NULL,
    ifsc_code           VARCHAR2(11 CHAR) NOT NULL,
    bank_name           VARCHAR2(200 CHAR) NOT NULL,
    beneficiary_status  VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    activated_at        TIMESTAMP(6),
    created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_beneficiary PRIMARY KEY (beneficiary_id),
    CONSTRAINT uq_beneficiary_nickname UNIQUE (customer_id, nickname),
    CONSTRAINT uq_beneficiary_account UNIQUE (customer_id, account_number, ifsc_code),
    CONSTRAINT ck_beneficiary_account_number CHECK (
        REGEXP_LIKE(account_number, '^[0-9]{10,20}$')
    ),
    CONSTRAINT ck_beneficiary_ifsc_upper CHECK (ifsc_code = UPPER(ifsc_code)),
    CONSTRAINT ck_beneficiary_ifsc_format CHECK (
        REGEXP_LIKE(ifsc_code, '^[A-Z]{4}0[A-Z0-9]{6}$')
    ),
    CONSTRAINT ck_beneficiary_status CHECK (
        beneficiary_status IN ('PENDING', 'ACTIVE', 'DISABLED', 'REJECTED')
    ),
    CONSTRAINT ck_beneficiary_activated CHECK (
        (beneficiary_status = 'ACTIVE' AND activated_at IS NOT NULL)
        OR beneficiary_status <> 'ACTIVE'
    )
);

CREATE OR REPLACE TRIGGER trg_beneficiary_set_updated_at
BEFORE UPDATE ON beneficiary
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE biller (
    biller_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    biller_code VARCHAR2(40 CHAR) NOT NULL,
    biller_name VARCHAR2(200 CHAR) NOT NULL,
    category VARCHAR2(60 CHAR) NOT NULL,
    reference_label VARCHAR2(100 CHAR) NOT NULL,
    min_amount NUMBER(19,4) DEFAULT 1 NOT NULL,
    max_amount NUMBER(19,4) DEFAULT 100000 NOT NULL,
    is_active CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_biller PRIMARY KEY (biller_id),
    CONSTRAINT uq_biller_code UNIQUE (biller_code),
    CONSTRAINT ck_biller_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT ck_biller_amounts CHECK (min_amount > 0 AND max_amount >= min_amount)
);
ALTER TABLE biller ADD (reference_pattern VARCHAR2(200 CHAR));
INSERT INTO biller (biller_code,biller_name,category,reference_label,reference_pattern) VALUES ('ELECTRICITY','Demo Electricity Board','UTILITIES','Consumer number','^[0-9]{6,20}$');
INSERT INTO biller (biller_code,biller_name,category,reference_label,reference_pattern) VALUES ('MOBILE','Demo Mobile Services','TELECOM','Mobile number','^[0-9]{10}$');
INSERT INTO biller (biller_code,biller_name,category,reference_label,reference_pattern) VALUES ('WATER','Demo Water Authority','UTILITIES','Connection number','^[A-Za-z0-9][A-Za-z0-9-]{4,29}$');
CREATE TABLE payment_operation (
    payment_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    kind VARCHAR2(20 CHAR) NOT NULL,
    operation_key VARCHAR2(64 CHAR) NOT NULL UNIQUE,
    user_id NUMBER(19) NOT NULL,
    request_key VARCHAR2(100 CHAR) NOT NULL,
    request_fingerprint VARCHAR2(64 CHAR) NOT NULL,
    intent_digest VARCHAR2(64 CHAR) NOT NULL,
    ledger_command CLOB NOT NULL,
    payment_details CLOB NOT NULL,
    state VARCHAR2(20 CHAR) NOT NULL,
    transaction_id NUMBER(19) UNIQUE,
    transaction_reference VARCHAR2(50 CHAR) UNIQUE,
    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_payment_request UNIQUE(user_id,kind,request_key),
    CONSTRAINT ck_payment_kind CHECK(kind IN ('TRANSFER','BILL_PAYMENT')),
    CONSTRAINT ck_payment_state CHECK(state IN ('AWAITING_OTP','AUTHORIZED','COMPLETED','FAILED')),
    CONSTRAINT ck_payment_receipt CHECK(state <> 'COMPLETED' OR (transaction_id IS NOT NULL AND transaction_reference IS NOT NULL))
);
CREATE INDEX ix_payment_recovery ON payment_operation(state,created_at);
