CREATE TABLE forex_quote (
    quote_id VARCHAR2(36 CHAR) PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    source_account_id NUMBER(19) NOT NULL,
    destination_account_id NUMBER(19) NOT NULL,
    source_currency CHAR(3 CHAR) NOT NULL,
    destination_currency CHAR(3 CHAR) NOT NULL,
    source_amount NUMBER(19,4) NOT NULL,
    destination_amount NUMBER(19,4) NOT NULL,
    exchange_rate NUMBER(19,8) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_forex_quote_amount CHECK (source_amount > 0 AND destination_amount > 0),
    CONSTRAINT ck_forex_quote_rate CHECK (exchange_rate > 0),
    CONSTRAINT ck_forex_quote_pair CHECK (source_currency <> destination_currency),
    CONSTRAINT ck_forex_quote_accounts CHECK (source_account_id <> destination_account_id)
);
CREATE INDEX ix_forex_quote_user ON forex_quote(user_id, created_at);

CREATE TABLE forex_conversion (
    conversion_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    quote_id VARCHAR2(36 CHAR) NOT NULL REFERENCES forex_quote(quote_id),
    user_id NUMBER(19) NOT NULL,
    request_key VARCHAR2(64 CHAR) NOT NULL,
    request_fingerprint VARCHAR2(64 CHAR) NOT NULL,
    operation_id VARCHAR2(36 CHAR) NOT NULL,
    state VARCHAR2(20 CHAR) NOT NULL,
    debit_transaction_id NUMBER(19),
    debit_reference VARCHAR2(50 CHAR),
    credit_transaction_id NUMBER(19),
    credit_reference VARCHAR2(50 CHAR),
    created_at TIMESTAMP(6) NOT NULL,
    next_attempt_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_forex_conversion_quote UNIQUE(quote_id),
    CONSTRAINT uq_forex_conversion_request UNIQUE(user_id, request_key),
    CONSTRAINT uq_forex_conversion_operation UNIQUE(operation_id),
    CONSTRAINT ck_forex_conversion_state CHECK(state IN ('AWAITING_OTP','AUTHORIZED','COMPLETED','FAILED')),
    CONSTRAINT ck_forex_conversion_receipt CHECK(state <> 'COMPLETED' OR
        (debit_transaction_id IS NOT NULL AND debit_reference IS NOT NULL
         AND credit_transaction_id IS NOT NULL AND credit_reference IS NOT NULL))
);
CREATE INDEX ix_forex_conversion_recovery ON forex_conversion(state, next_attempt_at);
CREATE INDEX ix_forex_conversion_history ON forex_conversion(user_id, created_at, conversion_id);
