package com.netbanking.ledger;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;

import com.netbanking.ServiceTestBase;
import com.netbanking.contracts.*;
import com.netbanking.discovery.CustomerDirectory;
import com.netbanking.ledger.external.ExternalTransferAdapter;
import com.netbanking.ledger.external.ExternalTransferCommand;
import com.netbanking.ledger.external.ExternalTransferReceipt;
import com.netbanking.ledger.service.LedgerService;
import com.netbanking.ledger.service.DepositLedgerService;

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.bean.override.mockito.MockitoBean;

import java.math.BigDecimal;
import java.util.concurrent.*;

class LedgerIntegrationTest extends ServiceTestBase {
    @Autowired JdbcTemplate jdbc;
    @Autowired LedgerService ledger;
    @Autowired DepositLedgerService depositLedger;
    @MockitoBean CustomerDirectory customers;
    @MockitoBean ExternalTransferAdapter externalTransfers;

    @BeforeEach
    void seed() {
        jdbc.execute(
                "CREATE TABLE IF NOT EXISTS ledger_operation(caller VARCHAR(50),operation_id"
                        + " VARCHAR(64),request_fingerprint VARCHAR(64),receipt CLOB,PRIMARY"
                        + " KEY(caller,operation_id))");
        jdbc.execute(
                "CREATE TABLE IF NOT EXISTS event_outbox(event_id VARCHAR(36) PRIMARY"
                        + " KEY,destination VARCHAR(50),envelope CLOB)");
        jdbc.execute(
                "CREATE TABLE IF NOT EXISTS external_transfer_dispatch("
                    + "external_transfer_dispatch_id BIGINT GENERATED BY DEFAULT AS IDENTITY"
                    + " PRIMARY KEY,operation_id VARCHAR(64) UNIQUE,transaction_id BIGINT,"
                    + "provider_reference VARCHAR(100) UNIQUE,dispatch_status VARCHAR(20),"
                    + "dispatched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        for (String table :
                new String[] {
                    "event_outbox",
                    "external_transfer_dispatch",
                    "ledger_operation",
                    "account_transaction_entry",
                    "bank_transaction_status_history",
                    "bank_transaction",
                    "account_holder",
                    "bank_account",
                    "branch"
                }) jdbc.update("DELETE FROM " + table);
        jdbc.update(
                "INSERT INTO"
                    + " branch(branch_id,bank_id,branch_code,branch_name,ifsc_code,city,state,is_active)"
                    + " VALUES(1,1,'MAIN','Main','ABCD0001234','City','State','Y')");
        for (int id = 1; id <= 2; id++) {
            jdbc.update(
                    "INSERT INTO"
                        + " bank_account(account_id,branch_id,account_number,account_type,currency_code,account_status,current_balance,available_balance)"
                        + " VALUES(?,1,?,'SAVINGS','INR','ACTIVE',1000,1000)",
                    id,
                    "123456789" + id);
            jdbc.update(
                    "INSERT INTO account_holder(account_id,customer_id,is_active,holder_type)"
                            + " VALUES(?,11,'Y','PRIMARY')",
                    id);
        }
        when(customers.requireCustomerIdForUser(7L)).thenReturn(11L);
    }

    LedgerCommand command(String key, Long source, String destination, String amount) {
        return command(key, source, destination, "ABCD0001234", amount);
    }

    LedgerCommand command(
            String key, Long source, String destination, String ifsc, String amount) {
        return new LedgerCommand(
                key,
                7L,
                source,
                21L,
                destination,
                ifsc,
                "TRANSFER",
                new BigDecimal(amount),
                "INR",
                "Test");
    }

    BigDecimal balance(long id) {
        return jdbc.queryForObject(
                "SELECT current_balance FROM bank_account WHERE account_id = ?",
                BigDecimal.class,
                id);
    }

    LedgerCommand withdrawal(String key, String amount) {
        return new LedgerCommand(
                key,
                7L,
                1L,
                null,
                null,
                null,
                "WITHDRAWAL",
                new BigDecimal(amount),
                "INR",
                "Bill payment: TEST");
    }

    @Test
    void forexConversionPostsTwoCurrenciesAtomicallyAndOnlyOnce() {
        jdbc.update("UPDATE bank_account SET currency_code='USD' WHERE account_id=2");
        var command = new ForexLedgerCommand("fx-1", 7L, 1L, 2L,
                new BigDecimal("850.0000"), new BigDecimal("10.0000"), "INR", "USD");

        var first = ledger.convert("payments-service", command);
        assertThat(ledger.convert("payments-service", command)).isEqualTo(first);
        assertThat(balance(1)).isEqualByComparingTo("150.0000");
        assertThat(balance(2)).isEqualByComparingTo("1010.0000");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM bank_transaction", Integer.class))
                .isEqualTo(2);
        assertThat(first.debitReference()).isNotEqualTo(first.creditReference());
        assertThatThrownBy(() -> ledger.convert("products-service", command))
                .isInstanceOf(SecurityException.class);
    }

    @Test
    void forexConversionRollsBackWhenSourceFundsAreInsufficient() {
        jdbc.update("UPDATE bank_account SET currency_code='USD' WHERE account_id=2");
        var command = new ForexLedgerCommand("fx-insufficient", 7L, 1L, 2L,
                new BigDecimal("1500.0000"), new BigDecimal("17.0000"), "INR", "USD");
        assertThatThrownBy(() -> ledger.convert("payments-service", command))
                .isInstanceOf(IllegalStateException.class);
        assertThat(balance(1)).isEqualByComparingTo("1000.0000");
        assertThat(balance(2)).isEqualByComparingTo("1000.0000");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM bank_transaction", Integer.class))
                .isZero();
    }

    @Test
    void commitsBothBalancesEntriesAndOutboxOnce() {
        var request = command("transfer-1", 1L, "1234567892", "100.1234");
        var first = ledger.post("payments-service", request);
        assertThat(ledger.post("payments-service", request)).isEqualTo(first);
        assertThat(balance(1)).isEqualByComparingTo("899.8766");
        assertThat(balance(2)).isEqualByComparingTo("1100.1234");
        assertThat(
                        jdbc.queryForObject(
                                "SELECT COUNT(*) FROM account_transaction_entry", Integer.class))
                .isEqualTo(2);
        assertThat(
                        jdbc.queryForObject(
                                "SELECT beneficiary_id FROM bank_transaction", Long.class))
                .isEqualTo(21L);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM event_outbox", Integer.class))
                .isEqualTo(1);
        assertThatThrownBy(
                        () ->
                                ledger.post(
                                        "payments-service",
                                        command("transfer-1", 1L, "1234567892", "101")))
                .isInstanceOf(com.netbanking.common.exception.ConflictException.class);
    }

    @Test
    void failureAfterDebitRollsBackTheEntireLedgerTransaction() {
        jdbc.update("UPDATE bank_account SET account_status='FROZEN' WHERE account_id=2");
        assertThatThrownBy(
                        () ->
                                ledger.post(
                                        "payments-service",
                                        command("rollback", 1L, "1234567892", "100")))
                .isInstanceOf(IllegalStateException.class);
        assertThat(balance(1)).isEqualByComparingTo("1000");
        assertThat(balance(2)).isEqualByComparingTo("1000");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM bank_transaction", Integer.class))
                .isZero();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ledger_operation", Integer.class))
                .isZero();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM event_outbox", Integer.class))
                .isZero();
    }

    @Test
    void oppositeDirectionTransfersAndDuplicateRequestsPreserveBalances() throws Exception {
        var pool = Executors.newFixedThreadPool(4);
        var start = new CountDownLatch(1);
        try {
            var forward = command("forward", 1L, "1234567892", "100");
            var reverse = command("reverse", 2L, "1234567891", "40");
            var tasks =
                    java.util.List.of(forward, forward, reverse, reverse).stream()
                            .map(
                                    c ->
                                            pool.submit(
                                                    () -> {
                                                        start.await();
                                                        return ledger.post("payments-service", c);
                                                    }))
                            .toList();
            start.countDown();
            for (var task : tasks) task.get(15, TimeUnit.SECONDS);
            assertThat(balance(1)).isEqualByComparingTo("940");
            assertThat(balance(2)).isEqualByComparingTo("1060");
            assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM bank_transaction", Integer.class))
                    .isEqualTo(2);
        } finally {
            pool.shutdownNow();
        }
    }

    @Test
    void selfTransferAndUnknownLocalDestinationCannotDebit() {
        assertThatThrownBy(
                        () ->
                                ledger.post(
                                        "payments-service",
                                        command("self", 1L, "1234567891", "100")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(
                        () ->
                                ledger.post(
                                        "payments-service",
                                        command("external", 1L, "9999999999", "100")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThat(balance(1)).isEqualByComparingTo("1000");
        verifyNoInteractions(externalTransfers);
    }

    @Test
    void externalTransferDebitsOnceAndRecordsTheProviderReference() {
        var request = command("external", 1L, "9999999999", "WXYZ0001234", "100");
        when(externalTransfers.transfer(any(ExternalTransferCommand.class)))
                .thenReturn(new ExternalTransferReceipt("MOCK-REFERENCE", "ACCEPTED"));

        var first = ledger.post("payments-service", request);

        assertThat(ledger.post("payments-service", request)).isEqualTo(first);
        assertThat(balance(1)).isEqualByComparingTo("900");
        assertThat(balance(2)).isEqualByComparingTo("1000");
        assertThat(
                        jdbc.queryForObject(
                                "SELECT COUNT(*) FROM account_transaction_entry", Integer.class))
                .isEqualTo(1);
        assertThat(
                        jdbc.queryForObject(
                                "SELECT provider_reference FROM external_transfer_dispatch",
                                String.class))
                .isEqualTo("MOCK-REFERENCE");
        verify(externalTransfers, times(1)).transfer(any(ExternalTransferCommand.class));
    }

    @Test
    void externalProviderFailureRollsBackTheDebitForRecovery() {
        var request = command("external-failure", 1L, "9999999999", "WXYZ0001234", "100");
        when(externalTransfers.transfer(any(ExternalTransferCommand.class)))
                .thenThrow(
                        new org.springframework.web.server.ResponseStatusException(
                                org.springframework.http.HttpStatus.SERVICE_UNAVAILABLE,
                                "provider unavailable"));

        assertThatThrownBy(() -> ledger.post("payments-service", request))
                .isInstanceOf(org.springframework.web.server.ResponseStatusException.class);

        assertThat(balance(1)).isEqualByComparingTo("1000");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM bank_transaction", Integer.class))
                .isZero();
        assertThat(
                        jdbc.queryForObject(
                                "SELECT COUNT(*) FROM external_transfer_dispatch", Integer.class))
                .isZero();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ledger_operation", Integer.class))
                .isZero();
    }

    @Test
    void billDebitReversalCreditsTheSourceExactlyOnce() {
        var debit = ledger.post("payments-service", withdrawal("bill-payment", "100"));
        var command =
                new LedgerReversalCommand(
                        "bill-payment:reversal", 7L, debit.transactionId(), "Biller rejected bill");

        var first = ledger.reverse("payments-service", command);

        assertThat(ledger.reverse("payments-service", command)).isEqualTo(first);
        assertThat(balance(1)).isEqualByComparingTo("1000");
        assertThat(
                        jdbc.queryForObject(
                                "SELECT transaction_status FROM bank_transaction WHERE"
                                        + " transaction_id = ?",
                                String.class,
                                debit.transactionId()))
                .isEqualTo("REVERSED");
        assertThat(
                        jdbc.queryForObject(
                                "SELECT COUNT(*) FROM bank_transaction WHERE transaction_type ="
                                        + " 'REVERSAL'",
                                Integer.class))
                .isEqualTo(1);
    }

    @Test
    void depositFundingAndPayoutAreIdempotentAndOwned() {
        var fund = new DepositLedgerCommand("fd-open-1", 7L, 1L, "FUND",
                new BigDecimal("200.00"), "FD opening");
        var funding = depositLedger.post(fund);
        assertThat(depositLedger.post(fund)).isEqualTo(funding);
        assertThat(balance(1)).isEqualByComparingTo("800");

        var payout = new DepositLedgerCommand("fd-mature-1", 7L, 1L, "PAYOUT",
                new BigDecimal("210.00"), "FD maturity");
        var paid = depositLedger.post(payout);
        assertThat(depositLedger.post(payout)).isEqualTo(paid);
        assertThat(balance(1)).isEqualByComparingTo("1010");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM bank_transaction", Integer.class))
                .isEqualTo(2);
        assertThatThrownBy(() -> depositLedger.post(new DepositLedgerCommand("fd-open-1", 7L,
                1L, "FUND", new BigDecimal("201.00"), "FD opening")))
                .isInstanceOf(com.netbanking.common.exception.ConflictException.class);
        assertThatThrownBy(() -> depositLedger.post(new DepositLedgerCommand("wrong-user", 8L,
                1L, "FUND", new BigDecimal("10"), "FD opening")))
                .isInstanceOf(RuntimeException.class);
    }

    @Test
    void rejectedDepositFundingLeavesNoLedgerEntry() {
        assertThatThrownBy(() -> depositLedger.post(new DepositLedgerCommand("too-much", 7L,
                1L, "FUND", new BigDecimal("2000"), "FD opening")))
                .isInstanceOf(IllegalStateException.class);
        assertThat(balance(1)).isEqualByComparingTo("1000");
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ledger_operation", Integer.class))
                .isZero();
    }
}
